### ISSUE TITLE
UI: tooltip hides some of the stereo options

### ISSUE THREAD

**Issue by mgerhardy** [PadWorld-Entertainment/worldofpadman#105]
It's especially hard to disable them if you activated them by accident as the tooltip hides the 'off' option.

**Comment by kai-li-wop** [comment]
Yes, I've noticed that as well. I could no longer disable the option via the menu and had to do it via the console via "r_anaglypgmode 0". I just hadn't thought it worthy of mentioning here yet.
So far the dropdown menus are always aligned to the middle entry, so they open centered. Maybe you could align them to the first entry, so with top-alignment. But there might be problems if a dropdown is opened quite far down the screen, see Gametype selection in the Create menu.
