### ISSUE TITLE
UI: Console spams WARNING: Stream dropping raw samples, reached MAX_STREAM_Buffers when plying intro movie

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#107]
Console keeps spamming 'WARNING: Stream dropping raw samples, reached MAX_STREAM_Buffers' when plying intro movie.
![grafik](https://user-images.githubusercontent.com/44040989/116919806-200dc080-ac52-11eb-9c04-7986a61802cf.png)

**Comment by mgerhardy** [comment]
There is an interesting comment in the code:

```c
// Q3A cinematics use up to 12 buffers at once
#define MAX_STREAM_BUFFERS 20
```

maybe the ogv is using even more. Will investigate.

**Comment by kai-li-wop** [comment]
@mgerhardy: I have to say that this problem has gotten worse. I can hear the intro movie sound really crackle and stutter, and I'm now getting 50 or more of these console messages. At first I thought it was related to recent code changes, but I went back in the build history and also tested binaries that are almost a month old with the same result. I am using a USB headset right now, not my speakers which are connected directly to the motherboard sound card. Can it be related to the sound device? I can't change it back right now to test it unfortunately as I would disturb others here in the room.

**Comment by kai-li-wop** [comment]
This issue was not occurring while testing any more and is fixed in my point of view.
