### ISSUE TITLE
UI: Empty demo menu but demo files are present in user folder

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#108]
Should have been fixed by now and worked in the new engine, but it doesn't work in the current build. There are _71 demo files present in the wop user folder in demos.

![shot0000](https://user-images.githubusercontent.com/44040989/116919960-59dec700-ac52-11eb-9b48-c7b392966dce.jpg)

**Comment by mgerhardy** [comment]
Could you please attach one of them?

**Comment by kai-li-wop** [comment]
Demos were recorded with the old 1.6 client.
[demos.zip](https://github.com/PadWorld-Entertainment/worldofpadman/files/6417065/demos.zip)

**Comment by mgerhardy** [comment]
the demo extension was changed to `wopdemo_` (it was `dm_`). Not sure why it was changed. Will change it back.

**Comment by kai-li-wop** [comment]
This was one of the changes of @codemasher in master branch but was not cherry picked into main. I don't know how it found its way.
