### ISSUE TITLE
Distribution: Snap Store / Gnome Software

### ISSUE THREAD

**Issue by digidigital** [PadWorld-Entertainment/worldofpadman#108]
I have tried snapping the game (1.6.1) and it was the easiest snap I ever made :)
The base game seems to work almost "out of the box". 

You would be able to install it from the snap store and start it from your desktop / app launcher like any other software.

Since snaps run in a restricted environment you can not drop custom maps / mods / models in the wop-folder.
Instead you have to put them in the ~/snap/wop/current/.padman/wop folder. Since this folder is versioned you have to copy the custom files to the next "current" folder after each update. This somewhat contradicts the idea of simplifying the installation and general handling.

Another approach could be to write a small Padman-Installer/Launcher GUI that downloads and installs the game in a persistent and writable folder -> SNAP_COMMON.  I have not tested if you can execute files in that folder, yet.  
If it is working adding / removing additional content could be done in this application as well.
In this case we would need a reliable server that hosts the game files without captchas or token links (or grab the token links from the website). 

From your perspective, is it at all desirable to have the game in the Snap Store? Any license issues?

**Comment by 3aTmE** [comment]
@digidigital just wanted to thank you for your work. I've installed WoP using your snap on my laptop recently and it was the easiest, laziest ( in the very best way possible) installation of WoP I've ever experienced. Makes you kinda wish to see WoP on other digital distribution platforms :)

Thank you for your effort!
