### ISSUE TITLE
possible bug/spaghetti in g_combat.c

### ISSUE THREAD

**Issue by codemasher** [PadWorld-Entertainment/worldofpadman#11]
Um what is going on here? Is it a leftover from something? Also can it possibly be reduced to:

```c
 	if ( self->client->sess.sessionTeam == TEAM_BLUE ) { 
 		classname = "team_CTL_bluelolly"; 
 	} 
 	else { 
 		classname = "team_CTL_redlolly"; 
 	} 
```

https://github.com/PadWorld-Entertainment/wop-engine/blob/7ce31f4f670ac0820ccb6d210cfbbb86dd297c82/code/game/g_combat.c#L338-L354

**Comment by mgerhardy** [comment]
:+1:

**Comment by zturtleman** [comment]
Looks like a leftover from Quake 3: Team Arena's 1 flag CTF gametype (take center neutral flag to enemy base).

**Comment by codemasher** [comment]
That makes sense! I've completely forgot that one flag CTF even existed... :laughing:
