### ISSUE TITLE
HUD: Voice chat icon not shown ingame

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#117]
In WoP 1.6, the voice chat icon above the player's head was displayed through walls due to a missing shader. With WoP 1.6.1 and 1.6.2, it has now unfortunately disappeared completely. If a player is using voice chat, it will not be displayed above his head.

**Comment by kai-li-wop** [comment]
7f2fb2169f3f43e6026fe1ea225bb51dc6fe6414 fixes a wrong shader path but the icon is still not shown. Could only test on a local client game, not online.

**Comment by mgerhardy** [comment]
should be fixed - feedback welcome

**Comment by kai-li-wop** [comment]
Under what conditions can you test this? I just started a local game and then went to the 3rd person view. As long as I start recording with the PushToTalk button, no microphone icon is displayed above my player character. I remember the feature used to work the same like the WoP icon above the player character in normal text chat. Maybe it is only possible to test in online matches with other players. This would need to wait until a server is up and running beta tests.

**Comment by mgerhardy** [comment]
As far as I can say you don't see it for yourself (on purpose)

`CG_DrawVoiceNames`
contains
```
		if (i == cg.predictedPlayerState.clientNum)
			continue;
```

**Comment by 3aTmE** [comment]
Using the Current Codebase i can Confirm that the Voice Chat Icons show up properly in-game:

![VC](https://user-images.githubusercontent.com/84514074/165850563-6da649fd-c0ac-4504-98ed-586fb57c9a80.png)

Tested on a local game.

**Comment by kai-li-wop** [comment]
Excellent!
