### ISSUE TITLE
Better accessibility for the command-console

### ISSUE THREAD

**Issue by MancusNemo** [PadWorld-Entertainment/worldofpadman#118]
The console in World of Padman is hard and difficult to read. The problem could be solved with a changeable background colour or with a solution from quake3e /con_scale.

Source for /con_scale solution:
https://github.com/ec-/Quake3e/commit/2bdc3692a7d7fbb9af4297c78762c1ef1f9bcb85

**Comment by mgerhardy** [comment]
Which resolution are you running wop with? It looks like we are talking about two different things here. The color of the font and background makes it hard to read? Or the font size?

**Comment by MancusNemo** [comment]
No not about two different things, but about two possible solutions to a problem.

One can be to change the font size. The other is to change the background colour. Each measure can improve the readability. And thus solve the problem.

As screens get higher and higher resolutions, I would still scale the font up. To be prepared for the future for 4k and more.

To help the visually impaired, I would still make the background colour editable!

**Comment by kai-li-wop** [comment]
We should implement the con_scale feature to scale the font size of the console. We need to see how this interferes with the changes raute made to the chat notifications, if the is relevant.

**Comment by kai-li-wop** [comment]
I had a look at it, but the source code of World of Padman in cl_console.c is already very different from Quake3e. We should definitely adopt the feature, only I can't estimate what other optimizations and enhancements have been done there. In this respect I leave the implementation to @mgerhardy, because my knowledge is not sufficient for this. ;)

**Comment by MancusNemo** [comment]
Ok, sounds good! Thank you! :)

**Comment by kai-li-wop** [comment]
Linking this 038ce0f5fdc9af040f78a5bdaf5f95669d5f54c2 as an implementation.

**Comment by kai-li-wop** [comment]
@mgerhardy: I just tested this feature, so far so good. But somehow the characters are now very close together, especially for the numbers, which makes it difficult to read. The font used to be monospace (not proportional), but now the characters overlap, making it difficult to read. Also, the characters in the console used to be displayed scaled to half width. Perhaps the proportional and non-proportional fonts are now somehow mixed in World of Padman? Perhaps there is simply no minimum spacing between the characters. So something doesn't quite fit together yet.

Compare old vs. new (screenshots show different console content)
![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/4b7551a4-63c7-4bb5-96e0-a4e8f211b91f)

![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/414d3d1e-3aaa-4e34-8b6c-31b9cfcbed02)

**Comment by kai-li-wop** [comment]
@mgerhardy: Super, this fixed it for me.

**Comment by kai-li-wop** [comment]
5dba1b6e30ab69e0ebdf85830658c3eb40189694 introduces a menu option for this --> game preferences / chat page

![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/48d771ea-cb2a-4e45-aec7-dcf525968222)

**Comment by 3aTmE** [comment]
Works as intended! 
Was able to scale the Font in the Console without any issues using the Options -> Chat Menu.
