### ISSUE TITLE
Changing Win 10 scaling when the game is open results in an endless restarting

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#122]
Originally reported by Imagine:

"Changing scaling (on Windows 10) when the game is open results in an endless restarting - until hitting Alt+Enter, resulting in black bars at the top (going into setup it changes the resolution from 1920x1080 to 1280x720).

Imagine captured the following video:

https://user-images.githubusercontent.com/44040989/150832375-09826527-7686-4d2d-b243-600457bc9d75.mp4

**Comment by kai-li-wop** [comment]
Would be interesting to see if this also happens with ioquake3.

**Comment by 3aTmE** [comment]
> Would be interesting to see if this also happens with ioquake3.

Yes, It actually does!

https://user-images.githubusercontent.com/84514074/154152206-1c2fa95a-193f-48a9-930e-9fa398e96813.mp4

**Comment by kai-li-wop** [comment]
We should ask for a fix upstream then. :D

**Comment by mgerhardy** [comment]
this might be hidden in `GLimp_EndFrame`. and maybe is related to how sdl is handling the window in case of zooming. does this also happen when you start wop in windowed mode?

Maybe this update of SDL (atm to 2.0.21) https://github.com/PadWorld-Entertainment/worldofpadman/pull/128 helps here.

**Comment by 3aTmE** [comment]
> this might be hidden in `GLimp_EndFrame`. and maybe is related to how sdl is handling the window in case of zooming. does this also happen when you start wop in windowed mode?
> 
> Maybe this update of SDL (atm to 2.0.21) #128 helps here.

Yes! This example is taken from Quake3 but im sure that wop itself will also behave the same. 

https://user-images.githubusercontent.com/84514074/154707534-6b6bea17-c408-4572-aa04-38e71e22014b.mp4

**Comment by kai-li-wop** [comment]
I tested the issue this morning with updated SDL 2.0.20 but the behavior is the same. So we will see if upcoming SDL 2.0.21 update will do the trick.

**Comment by kai-li-wop** [comment]
We updated SDL to version 2.27.0 dev which will be kept up-to-date (see f4d1ea1e7f10c0046d240c61092f01b40a3df0eb). So it is worth to try to test the issue again if it is fixed with the new sdl version.

**Comment by kai-li-wop** [comment]
@3aTmE: I don't seem to have the bug since the last SDL update. I know you can't check this because you don't have a Win10 system available, but maybe someone else can test the issue and you can possibly help get the latest WoP 1.7dev working for them?
