### ISSUE TITLE
Cancel intro video requires double mouse click of a menu button

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#123]
That's a little strange behavior. When WoP is started in window mode and as long as the intro video is playing, the mouse cursor is unbound, i.e. it can move freely beyond the window. If you then click into the window, which leads to the intentional termination of the intro video, you have to click a desired menu button twice afterwards in order to call up the corresponding menu page. If, on the other hand, the intro video is terminated with the Esc key or the space bar, one click on a button is sufficient to call up the desired menu page.  It looks as if, when the video is aborted by the mouse click, the focus is not on the menu and you have to click on it again in addition. This behavior has occurred in Windows 10.

1. Start WoP in window mode
2. Don't interrupt the intro by clicking the mouse --> afterwards menu buttons works with one click (normal behavior)
3. Interrupt the intro video by clicking the mouse --> afterwards menu buttons needs 2 clicks to work (buggy behavior)

**Comment by kai-li-wop** [comment]
I cannot reproduce this since aa0e53e4b1ea923aed0a249973379cff5959f3ca. Maybe it got fixed coincidently with it or way before.

**Comment by 3aTmE** [comment]
I was unable to replicate this issue with the recent code base. 

Seems to be fixed. 👍
