### ISSUE TITLE
SOUND: New surface parameter for splash footstep sounds

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#127]
Walking through flat water as a player already causes splashy footsteps sounds to be played. The issue is that there are solid  water-like surface textures in the game which cannot contain the surfaceparm water. They simply mimic a water surface like a small puddle of water on the floor. The goal of the extensions is to enable the possibility to add a new surfaceparm splashsteps to a texture shader, so the splashy footstep sounds can be played, if a level designer wants it. As an alternative there should also be a common splashclip texture to add the splash footsteps sound effect via a clip texture.

- [x] Add a new surfaceparm SURF_SPLASHSTEPS and link it to EV_FOOTSPLASH
- [x] Add splashsteps to custinfoparms.txt
- [x] Add splashclip shader entry to common.shader
- [x] Add a splashclip texture to textures/common folder

**Comment by kai-li-wop** [comment]
Should already work with 038184cb672cca1d95eb9aeb04382e51bd14a586 but needs further testing. Try build 80 but don't forget to apply the updated custinfoparms.txt and the updated common.shader. A texture for the new clip shader is still missing but will be uploaded later.

**Comment by kai-li-wop** [comment]
Splashclip texture is added to common textures.

**Comment by 3aTmE** [comment]
Nice! Just tested it on my end! Worked like a charm.  Used it also in a shader of mine which also worked without an issue.

https://user-images.githubusercontent.com/84514074/154697000-1290faa1-8e6b-4883-abed-ae472ed9fb17.mp4

**Comment by kai-li-wop** [comment]
Excellent!
