### ISSUE TITLE
Capture the Lolly voice messages

### ISSUE THREAD

**Issue by MancusNemo** [PadWorld-Entertainment/worldofpadman#134]
Hello, the voice messages in Capture the Lolly are confusing because you are every time asking yourself who has the flag now?
Do you have an Idea to make this better? It is not an nice thing to ask every time who has now the flag in an game via voice.

**Comment by kai-li-wop** [comment]
I don't quite understand the problem yet. What is unclear to you, which team has the lolly or which player? The announcer clearly mentions the team as far as I know. In addition, the team overlay shows which player currently has the lolly. What would be your idea to make it clearer?

**Comment by MancusNemo** [comment]
Ok here is more. It looks like an ghost bug. When someone of the same team you are the sound says "Raccon has the enemy lolly". That confuses me. But where I can find the sound files to check out exact what is going on. Its an ugly and time intensive way to provocate the sound. An friend says no he has clear speaking and it says some other text like "Your team has the enemy lolly." That makees sense. So I am at the moment not in position to verificate the bug. But I am on it. I hope the problem/bug I have is now more clear.

**Comment by kai-li-wop** [comment]
Follow this link to find the CTL sound files. I am sure not all of them are used in the game. https://github.com/PadWorld-Entertainment/worldofpadman/tree/main/wop/sound.pk3dir/sound/feedback/teamplay

**Comment by kai-li-wop** [comment]
@MancusNemo: Any new leads on the bug? Otherwise, I'm closing this ticket with the note "will not be fixed".
