### ISSUE TITLE
Music: Music playlist is empty after starting new map

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#134]
The music player still has an issue. The music play list starts empty in a new locally created match. I can select songs for a playlist like I wish. When I chose "restart map" from the ingame menu, the next song is played, so autoswitch next song works. When I chose "next map" or "leave arena" and create a new local match, the playlist is complete empty again. Somehow the playlist is not saved.

**Comment by mgerhardy** [comment]
Could you please attach some screenshots - just to ensure that I don't do something stupidly wrong while reproducing it. For me it works all fine after "leave arena" and loading a new map. But I'm most likely doing something wrong.

**Comment by kai-li-wop** [comment]
Ha, look what I have found: "Playlist from disk too large for internal buffer (is 2262, max 2047), will be reset! I added the carnage music back from Mighty Pete and have a little more songs in the list then usuallay come with WoP. https://worldofpadman.net/download/addons-wop/carnage/

![console](https://user-images.githubusercontent.com/44040989/119272197-1ea63700-bc05-11eb-8e5c-f65c4e235ea2.jpg)

**Comment by kai-li-wop** [comment]
Also the message "Can't read ... menuloop.wav" seems to be true, there is no wav file, but ogg. But the engine should already prefer ogg over wav, or not?

**Comment by kai-li-wop** [comment]
The situation is much better, because the list keeps tracks saved and also continues to play after "next map" and also after "leave arena" and starting a new match. Only problem now is, that somehow on track is not selected and a gap appears. Also after redoing the procedure, more and more racks are going to be removed from the list. "next song on map change" option was enabled.

![shot0001](https://user-images.githubusercontent.com/44040989/119355540-af345400-bca5-11eb-8833-395e34a43575.jpg)
![shot0002](https://user-images.githubusercontent.com/44040989/119355542-afccea80-bca5-11eb-8f25-138dd00b8c52.jpg)
![shot0003](https://user-images.githubusercontent.com/44040989/119355545-afccea80-bca5-11eb-826d-a7402eccb6ca.jpg)

**Comment by mgerhardy** [comment]
should be fixed in aec6ff13de8c84cf01029e8acb3a53c0ca7887ab

**Comment by kai-li-wop** [comment]
Tested and considered as fixed. ;)
