### ISSUE TITLE
Allow 8× multi sampling in traditional (non-framebuffer) MSAA

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#135]
The goal is to enable 8× multi sampling (r_ext_multisample 8) in traditional (non-framebuffer) MSAA for World of Padman

- [x] OpenGL 1 renderer
- [x] OpenGL 2 renderer

Additional questions
- Is this also relevant for the Vulkan renderer?
- What is r_ext_framebuffer_multisample for?

**Comment by kai-li-wop** [comment]
See: https://github.com/ioquake/ioq3/pull/487

**Comment by kai-li-wop** [comment]
Introduced with 55cd12ff4b56b8dbb853708199b2b041c3a32290

**Comment by kai-li-wop** [comment]
Example picture MSAA Off (see in full screen) 
![shot0002](https://user-images.githubusercontent.com/44040989/158330228-a0709dd8-1014-40af-82b8-44ea75cba667.jpg)

Example picture MSAA 2x (see in full screen) 
![shot0003](https://user-images.githubusercontent.com/44040989/158330230-61e5a8e2-c0ef-4d46-b12c-8f51cec8a3b3.jpg)

Example picture MSAA 4x (see in full screen) 
![shot0004](https://user-images.githubusercontent.com/44040989/158330235-243aa0bf-50fe-4f4d-9417-bf2d7e52f318.jpg)

Example picture MSAA 8x (see in full screen) 
![shot0005](https://user-images.githubusercontent.com/44040989/158330237-eb875e31-6831-466f-ac07-f20d775bb679.jpg)

**Comment by mgerhardy** [comment]
There is no multisample support in the vulkan renderer yet - see https://github.com/PadWorld-Entertainment/worldofpadman/commit/de3ef9ad8e4e97cdd446c1c89cd40fd99813598a

**Comment by mgerhardy** [comment]
`r_ext_framebuffer_multisample` controlls the samples for fbos - http://damien.porquet.free.fr/msi/glexts/GL_EXT_framebuffer_multisample.txt.html

in other words - antialiasing for framebuffers

**Comment by kai-li-wop** [comment]
OK, then my questions are answered. Neither the Vulkan renderer is officially supported by WoP yet, nor do we provide an option for r_ext_framebuffer_multisample in the menu. So both are irrelevant for this ticket. Thx
