### ISSUE TITLE
UI:  Fuel gauge of the Floater exceeds the box

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#136]
### Description

Fuel Gauge of the floater exceeds the white box.
![floaterui1](https://user-images.githubusercontent.com/84514074/120035092-51ce3900-bffe-11eb-93f5-49d2ceb01f51.jpg)
_this screenshot was taken on the beta 1.6.1 PadWorld Server_

I was able to replicate this issue locally.

The Bug appeared on the 32 & 64bit versions and on the OpenGL 1 and 2 renderer.

Issue also prevailed after deletion of my wop.config file.

The World Of Padman install was mostly clean. The only other .pk3 installed at that moment was the PadPack map pack.

### My System

**OS:** Windows 10
**RAM:** 16 GB, DDR4
**CPU:** AMD Ryzen 5 3600
**GRAPHICS:** AMD Radeon x580
**WoP Version:** 1.6.1 Beta

### Additional Infos

The Bug does not occur if im Playing on a 1.6 server

Another player who are using the 1.6.1 beta version reported to me that they don't have this issue.
Seems also to be on my end.

**Comment by mgerhardy** [comment]
`CG_DrawHoldableItem` 1c8fea9dbad16191ac4987a362eda121cb242ee8

**Comment by mgerhardy** [comment]
Where you also able to use the floater longer than 8 seconds? This looks like at least 24 seconds. Is this reproducible? I've checked all `STAT_HOLDABLEVAR` entries. I currently can't explain this. Did you have any other holdable item before?

**Comment by 3aTmE** [comment]
> Where you also able to use the floater longer than 8 seconds? This looks like at least 24 seconds. Is this reproducible? I've checked all `STAT_HOLDABLEVAR` entries. I currently can't explain this. Did you have any other holdable item before?

It's still the regular 8 seconds fly time. The bar just empties far quicker.

It seems that I'm the only one where this issue popped up yet. Asked yesterday another player if they could check it locally. They had no problems. All rendered fine.

As for now: I can replicate this by creating a game locally or playing on the Beta 1.6.1 PadWorld server.

Servers running 1.6 are all fine.

When I'm back on my pc later I will try to reinstall the 1.6.1 patch just to see if that fixes it.

This also occured the first time while playing on the 1.6.1 beta PadWorld server.

I've played on it before and after the corruption by auto download was fixed. Maybe it had something to do with it? 

Anyways, I'll report if a new installation fix it or not

**Comment by 3aTmE** [comment]
I was able to reset the Fuel gauge to normal by:

- Deleting my `padman` folder inside  `appdata/roaming`
- Reinstalling the 1.6.1 Patch
- Grabbing the Killerducks, then the floater.

Im sure that the last one did actually the trick, but hey. It's showing up normal again.

I still don't know what possibly could have caused this.
Don't sure if i should this close either.

**Comment by 3aTmE** [comment]
![shot0183](https://user-images.githubusercontent.com/84514074/120082214-f6657f00-c0c1-11eb-8d51-25d6eac1af6a.jpg)
_It just reappeared_ after playing a little match against bots on the _PadWorld 1.6.1 beta server._

Ironically also in the same map like yesterday.

**Comment by kai-li-wop** [comment]
I also, like others today discovered this issue. 8 seconds item time seems to be good but simply the bar is scaled too big. Also when the fuel is emptied, the bar is not going down in small steps, but in big steps. Seems to me a scaling problem of the texture.
![shot0005](https://user-images.githubusercontent.com/44040989/120936879-8b8ff580-c70a-11eb-91bc-1408d56c5e75.jpg)
![shot0006](https://user-images.githubusercontent.com/44040989/120936881-90ed4000-c70a-11eb-88e9-48794ded1dfb.jpg)

**Comment by kai-li-wop** [comment]
When I test this offline, i.e. locally, with last dev version and timer enabled, it counts down normally. Very shortly before the fuel gauge expires, i.e. the bar has almost no height left, the timer suddenly jumps back to 8 and then counts down very quickly to 0 again until the bar is also no longer visible. So it counts down twice, but the bar appears normal. This is different from the issue behavior online.

**Comment by mgerhardy** [comment]
I can't reproduce these issues locally, in LAN or inet game.

**Comment by 3aTmE** [comment]
> I can't reproduce these issues locally, in LAN or inet game.

The issue appeared so far only on the Padworld beta server.

I can go online with an clean install there later when I'm home.

Is there something you want me to observe, check if the issue reappears?

Otherwise I'm just going to edit this comment with my outcome and console log.

**Comment by mgerhardy** [comment]
It doesn't happen if you connect to the local running dedicated server and connect with a separately running client?
Would you please try with the binaries (incl. qvms) that are attached to the build pipelines and send screenshots if the issue is still alive with those. I've added a printing of the timer value below the bar.

**Comment by 3aTmE** [comment]
> It doesn't happen if you connect to the local running dedicated server and connect with a separately running client?

Haven't tried that yet (never came into my mind to be honest 😅 ) but I will try this out with my current "unclean" install.

Ok, Clean install with the binaries from the build pipeline it is. 

Comment again when I'm done

**Comment by mgerhardy** [comment]
keep in mind that you have to use the qvms from the pipeline - not the ones from the pk3s

**Comment by 3aTmE** [comment]
**Local Dedicated server / Connected via a separately running client _unclean install_ **
![shot0302](https://user-images.githubusercontent.com/84514074/133329747-8eafb535-0475-429a-8657-aacee1ffc484.jpg)
Issue prevails. 

**Clean Install from the Build Pipeline (Build-number #451) _Without_ the new qvms**
![shot0303](https://user-images.githubusercontent.com/84514074/133330031-f8422107-dc08-4670-8a61-38112a6a8144.jpg)
Issue does not appear!

**Connecting to the PadWorld 1.6.1 Beta server**
![shot0304](https://user-images.githubusercontent.com/84514074/133330118-9db31745-8478-44e8-9e20-0c217013a97d.jpg)
Issue _reappears_

**Connecting to any WoP 1.6 Server**
![shot0307](https://user-images.githubusercontent.com/84514074/133330229-864a34dc-ccf6-4fd2-b31a-7300cc06410f.jpg)
Issue does not appear!

**Local Dedicated server / Connected via a separately running client | _Build #451_  _With_ the new qvms**
![shot0306](https://user-images.githubusercontent.com/84514074/133330551-e6661be7-a249-40a0-bbf4-e44f443f5fd9.jpg)
Issue doesn't appear. But i had to remove wop_007.pk3 from my `appdata/roaming/padman` folder to make the timer on the floater appear.

**Local Dedicated server / Connected via a separately running client | _Build #451_  _With_ the new qvms**
![shot0309](https://user-images.githubusercontent.com/84514074/133330985-0ae285a3-193a-40ed-95cb-ab8fb936c07c.jpg)
Issue does not appear! The timer is also nicely shown after the deletion of wop_007.pk3 (the one that has been downloaded via auto dl from the PadWorld1.6.1 Beta server) from `appdata/roaming/padman`.

**Comment by kai-li-wop** [comment]
All tests on @mgerhardy's server have worked fine so far. Hectic has also started to investigate the problem and it seems to be related to @robo9k's beryllium mod. We need to investigate here how this is caused by the mod, but it is not a problem on our side. I therefore consider the problem to be solved.
