### ISSUE TITLE
MENU: Not possible to rechose spray logo via player settings menu while ingame

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#138]
It is not possible to rechose the spray logo via the player settings menu while being ingame. This is a bug introduced probably with WoP 1.6.1 but reproducible in WoP 1.6.2 (also 1.7.0 dev). While the ingame menu "rechose logo" works flawless doing the same via the player settings menu is not successful while being in a match. When changing the logo there, it is shown changed in the menu but not when spraying the logo. 

Steps for reproduction:
1. Start a SYC match with bots
2. Go to player settings menu (Setup/Player)
3. Chose another spray logo
4. Head back to the match
5. Do a frag or two to collect cartridges
6. Go to spray room and spray your logo
7. The logo sprayed is not the new selected one from the playersettings but the one selected before
8. Go back to player settings menu
9. The logo shown there is the new one

It is not possible to reproduce this in WoP 1.6.0. After changing the logo in player settings menu and heading back into the match, a notification is drawn, that a new logo was selected. This is not happening in WoP 1.6.2 or 1.7.0 dev.

**Comment by kai-li-wop** [comment]
@3aTmE & @mgerhardy: Can you approve this issue and test it, if it is fixed with build #145? Not sure if this is really the right solution but it seems one line of code was missing. Got it from the diff between 1.6.0 and 1.7.0.

**Comment by kai-li-wop** [comment]
@mgerhardy: OK. I could see that the missing line of code was removed by you with e208d7dd6b3c00af68ea0582aa7176dc84c8a1cb due to fixing an unknown command message in the player setting menu reported by me. Maybe we can find another solution for the prior issue to fix it. Would it be possible to execute this line of code only if the player is already ingame or connected to a server? You can see that there was a comment containing 'if (connected)' as a hint.

**Comment by kai-li-wop** [comment]
Now there should be a solution with [build 146](https://github.com/PadWorld-Entertainment/worldofpadman/actions/runs/2021509206). Waiting for approval.

**Comment by 3aTmE** [comment]
Tried to reproduce this issue with the steps given using the current Codebase & Executables.

Works like it supposed to. 
The Issue is fixed.
