### ISSUE TITLE
Support for PNG screenshots

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#139]
It would be nice to have support for PNG screenshots available in WoP e.g. to create some high quality screenshots for presentation purposes directly in PNG format. There is a [PR for ioquake3](https://github.com/ioquake/ioq3/pull/262) by @zturtleman already taking care about a feature like that. I think it also contains a few fixes regarding JPEG support.
~~I also like the idea about giving the user control via the game menu in what format he/she wants to save a screenshot. We should offer here a drop down option to select the desired screenshot format (PNG, JPG, TGA). Simply to find a space for that.~~

Task to perform
- [x] Evaluate the PR code for compatibility
- [x] Check for [necessity of meta data as stated](https://github.com/ioquake/ioq3/pull/262#discussion_r103779552) by @robo9k 
- [x] Apply the PR code
- [x] Adopt the PR code to work with VULKAN renderer --> @mgerhardy 
- [x] ~~Add option to select screenshot format PNG, JPG or TGA to Setup menu~~
- [x] ~~(?)Then 'screenshot' command and format must be separate values~~
- [x] ~~(?)Set the screenshot format via new CVAR 'r_screenshotFormat' 0=TGA; 1=JPG; 2=PNG~~
- [x] ~~(?)Set 2=PNG the new default~~
- [x] ~~(?)Bind a key to 'screenshot' only and format is decided by 'r_screenshotFormat' then~~
- [x] Add a key binding option to Controls menu Misc page

**Comment by kai-li-wop** [comment]
@mgerhardy: I could use your help here. I would like to finalize this feature and to merge it into main. ;)
1. I cannot manage to include zlib.h header file in rendercommon/tr_public.h in a correct way. Do I need to add something to a makelist? Also I cannot adopt the PR code to work with the VULKAN renderer. I would be very glad if you could have a look and try to implement it in the same way like with the other renderers.
2. I need some opinion if my approach described in the bullets list marked with (?) is a suitable one.

**Comment by mgerhardy** [comment]
vulkan is done

about the screenshot type cvar - i have no strong opinion about it. as it's currently implemented in the three renderers, it's just about three lines of code - not much duplication. But it would most likely be easier for the user to make this a cvar and put into the menu. I would do this (if at all) in a separate PR.

**Comment by kai-li-wop** [comment]
The integration of screenshot format selection in the menu will be handled in an extra ticket #183.
To test the new screenshot feature use the following commands

- TGA: screenshot
- JPEG: screenshotJPEG
- PNG: screenshot PNG (new)

Would be good to test this with all available renderers. On Windows switching to vulkan will cause probably a crash since it is not officially supported yet.

**Comment by kai-li-wop** [comment]
Due to #184 you cannot test the feature via the 3 screenshot commands since only `screenshot` is the leftover command. Use the menu option in Setup/Display to chose the desired screenshot format.
