### ISSUE TITLE
UI: Bringing mouse acceleration options to controls / look menu

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#141]
The ioquake3 code provides mouse acceleration support, also in an extended way with an offset mode, applied in Quake Live. Smokin' Guns already implemented those menu options a long time ago. See below TTimo's text for further information regarding the feature.

ToDo
- [x] Add option to control cl_mouseAccel --> "Mouse Acceleration" --> integer 0 to 10 --> dropdown
- [x] Change "Mouse Acceleration" maybe to slider due to dropdown is drawn half off screen (see screenshot)?
- [x] Add option to control cl_mouseAccelStyle --> "Accel. Offset Style" --> integer 0 (Quake3) and 1 (Quake Live) --> radio button
- [x] Add option to control cl_mouseAccelOffset --> "Acceleration Offset" -- > float 0 to 50000 --> slider
- [x] "Accel. Offset Style" needs "Mouse Acceleration" to be ">0" otherwise grey it out (disable it)
- [x] "Acceleration Offset" needs "Mouse Acceleration" to be ">0"  and "Accel. Offset Style" to be "=1" otherwise grey it out (disable it) 
- [x] "Mouse Acceleration" set to "0" will also set "Accel. Offset Style" to "0"

![shot0001](https://user-images.githubusercontent.com/44040989/160997690-3b5f2402-cd50-4998-9df8-d01209ff667a.jpg)

-------------------------
### QuakeLive mouse acceleration
(written by TTimo from id)

I've been using an experimental mouse acceleration code for a while, and decided to make it available to everyone. Don't be too worried if you don't understand the explanations below, this is mostly intended for advanced players: To enable it, set cl_mouseAccelStyle 1 (0 is the default/legacy behavior)

New style is controlled with 3 cvars: sensitivity cl_mouseAccel cl_mouseAccelOffset

The old code (cl_mouseAccelStyle 0) can be difficult to calibrate because if you have a base sensitivity setup, as soon as you set a non zero acceleration your base sensitivity at low speeds will change as well. The other problem with style 0 is that you are stuck on a square (power of two) acceleration curve.

The new code tries to solve both problems:
Once you setup your sensitivity to feel comfortable and accurate enough for low mouse deltas with no acceleration (cl_mouseAccel 0), you can start increasing cl_mouseAccel and tweaking cl_mouseAccelOffset to get the amplification you want for high deltas with little effect on low mouse deltas.

cl_mouseAccel is a power value. Should be >= 1, 2 will be the same power curve as style 0. The higher the value, the faster the amplification grows with the mouse delta.

cl_mouseAccelOffset sets how much base mouse delta will be doubled by acceleration. The closer to zero you bring it, the more acceleration will happen at low speeds. This is also very useful if you are changing to a new mouse with higher dpi, if you go from 500 to 1000 dpi, you can divide your cl_mouseAccelOffset by two to keep the same overall 'feel' (you will likely gain in precision when you do that, but that is not related to mouse acceleration).

Mouse acceleration is tricky to configure, and when you do you'll have to re-learn your aiming. But you will find that it's very much forth it in the long run. If you try the new acceleration code and start using it, I'd be very interested by your feedback.

**Comment by kai-li-wop** [comment]
Mouse Acceleration dropdown is changed to slider format. 4e9fc2bf503496f992749d9ac1227413e06c488f

**Comment by kai-li-wop** [comment]
Last changes:
- Mouse acceleration offset max set to 50000 instead of 50
- Joystick threshold is deactivated when joystick is disabled
- Slider menu items indicate the value set next to the item bar (thx @mgerhardy for the code snippet)

There is still room for improvement:
- Adjusting the slider step interval depending on the given min-max values. So far this is fixed at 1, which makes no sense with a joystick threshold of 0.15 to 0.75 to be set. The step size could be defined similarly to the min-max values.
- The new value display next to the slider could show the decimal places depending on the currently set value. 2 digits for values <10, 1 digit for values <100 and 0 digits for values >=100.

![shot0000](https://user-images.githubusercontent.com/44040989/161099050-b1dba32c-6377-4908-99bb-62b215309bd0.jpg)

**Comment by 3aTmE** [comment]
After playing a bit with the settings i can report that it works like it supposed to.
A bit surprised how responsive mouselook can get!

Acceleration _feels_ aggressive but it might be just me perceiving it wrong since i am not used to it.
