### ISSUE TITLE
UI: Voice Threshold Slider not showing the input value

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#142]
Voice Threshold Slider on page Sound of the System menu does not shown the recently set input value when leaving the page and coming back. The value is always Null while the current set input value in fact is accepted and sets the value. I could trace this error back to WoP version 1.5.1.

**Comment by mgerhardy** [comment]
Should be fixed

**Comment by kai-li-wop** [comment]
I know. I have seen it. I am currently working on a bigger VoiP UI enhancement #143 right now (not committed yet), and I already have fixed it there. Doesn't matter, but I don't know why this line was commented out. I don't see a reason for it.
