### ISSUE TITLE
UI: Enhancing display options menu

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#150]
There are several new options available that should be added to display options. Others should be revised.

ToDo
- [x] Moving window mode option from Graphics to Display options
- [x] Add resize window option (radio button)
- [x] Add limit max fps option (radio button)
- [x] Add VSync option (radio button)
- [x] Add magenta-green to anaglyph 3D mode list as 4th item
- [x] Add color swap option for anaglyph 3D modes (radio button)
- [x] Fix: Cyan-red option always enable magenta-green. The list offers now only 4 of the 8 modes. Modes 5 to 8 can be enabled by using the color swap option
- [x] Re-introduce screen size option --> Used to have issues with the sky lens flare in the past. Seems not to work at all right now. Investigation needed.
- [x] Fix: Enabling greyscale always causes the apply button to be shown even after vid_restart without changes made afterwards.
- [x] Unifying function names and general cleanup
- [x] Provide proper tooltips for all display options
- [x] Handle input of negative values by using sliders which can happen when first using mouse and second keyboard. Set slider scale from 10 to 100.

**Comment by 3aTmE** [comment]
Works as intended except the Screen Size slider as mentioned above.

*Additional Information:*
Executable build from & using current Source 
OS: Win 10 
64 GB RAM
Graphics: Quadro 2000m 4 GB
