### ISSUE TITLE
UI: Enhancing graphic options menu

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#151]
Adjust the Graphics menu to respect new engine/renderer options and improve the settings templates

ToDo
- [x] Add option to change the renderer from OpenGL1 to OpenGL2 or Vulkan
- [x] Re-introduce an option to switch lighting method from lightmap back to vertex for very weak systems
- [x] Remove fullscreen option --> is now part of display options with more choices to select from
- [x] Split geometric detail option in models detail and curves detail to allow separate adjustment
- [x] Add maximum choice to curves detail --> default is now high (was medium)
- [x] Change compress textures back to radio button
- [x] Merge anisotropy option with texture filter option
- [x] Adjust graphic settings templates by names and values to respect changes (Minimum, Performance, Quality and Maximum)
- [x] Add 'Can it run WoP?' template for testing purposes of the OpenGL2 renderer and maximum settings
- [x] Unifying function names and general cleanup
- [x] Provide proper tooltips for all graphics options

**Comment by 3aTmE** [comment]
The Buttons works as intended, tooltips showing up properly, changing the renderer from `OpenGL1` to `OpenGL2` works without any issues. Trying to run the `Vulkan` renderer crashes the game.

+1 for the "Can it run WoP?" preset :)

Or to keep it short : Everything that should work, works fine except the `Vulkan` Renderer.

€ : Choosing any of the presets might apply its settings but will still show up as a `custom` preset ingame.
(as example : If im choosing "Can it run WoP" will still appear as "Custom" in menu even if the settings of this preset will be applied)



*Additional Information:*
Executable build from & using current Source 
OS: Win 10 
64 GB RAM
Graphics: Quadro 2000m 4 GB
