### ISSUE TITLE
UI: Graphics Settings always shows Custom if a preset was selected

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#152]
Choosing any of the presets might apply its settings but will still show up as a `custom` preset ingame.
(as example : If im choosing "Can it run WoP" will still appear as "Custom" in menu even if the settings of this preset will be applied)

_Originally posted by @3aTmE in https://github.com/PadWorld-Entertainment/worldofpadman/issues/151#issuecomment-1112642028_

**Comment by kai-li-wop** [comment]
Note to myself: The only preset that displays correctly after a restart is 'Performance'. All others are displayed as 'Custom' ...
... it looks like the color depth preset of 1 or 2 is causing this behavior. Especially in windowed mode, the color depth is always set to 'Desktop' (0), so the presets that try to set it to 16 bits (1) or 32 bits (2) have no effect. Thus, the preset conditions will not be met in such cases and will always be interpreted as 'custom'. As a result, all presets will now always set the color depth value to 'Desktop'.

**Comment by 3aTmE** [comment]
Issue seems to be fixed.
I tried all presets and exited / re-entered the menu. The Presets are all showing up properly.

Executeable build from and using most recent code base.
