### ISSUE TITLE
UI: Screen Size slider having now effect

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#153]
Once the screen size feature used to have issues with the sky lens flare in the past because it did not scale with the selected screen size. Now it seems not to work at all. Investigation needed. Probably this feature got disabled.

- WoP 1.1: Feature worked in the PadMod without issues
- WoP 1.2: Doesn't work and game don't know about the cvar cg_viewsize
- WoP 1.5: Doesn't work but game knows about the cvar cg_viewsize
- WoP 1.6: Doesn't work but game knows about the cvar cg_viewsize

**Comment by kai-li-wop** [comment]
A few code lines got removed from WoP to disable the feature. I temporary reimplemented the missing code by cross-checking with ioquake3 code base and the feature works now in my client. Apart from the missing texture/shader one can see the issue with the sky lens flare effect which is not downsized in the same way. More investigation needed how to deal with this problem. Decision needs to be made to omit the view size feature or adjust the sky lens flare feature to work with the view size feature.

![Image](https://user-images.githubusercontent.com/44040989/166569001-c4f90c21-8f23-46ec-ae09-9ecd134058ab.jpg)

**Comment by kai-li-wop** [comment]
This should be fixed now, except for the sky lens flare effect issue which should be handled extra and has nothing to do with the slider issue.

**Comment by 3aTmE** [comment]
The Screen Size Slider works like it should. 
But any drawn 2D Element outside of the Window will stay drawn. 

Looks quite messy after a while:
![shot0000](https://user-images.githubusercontent.com/84514074/167157507-031ed6cf-c4e8-420e-a179-f2c748e026c1.jpg)

On a side note : The Comicbook background that also shows on loading screens would be a perfect fit as a "border"

**Comment by kai-li-wop** [comment]
Looks like the HOM effect, which I faced with OpenGl2 renderer enabled. Please test with OpenGl1 enabled first.

**Comment by 3aTmE** [comment]
> Looks like the HOM effect, which I faced with OpenGl2 renderer enabled. Please test with OpenGl1 enabled first.

You're right! Using `OpenGL1` it's working like it should. The Background renders fine.
