### ISSUE TITLE
RENDERER: OpenGL2 causes HOM effect on window background

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#154]
The Screen Size Slider works like it should. But any drawn 2D Element outside of the Window will stay drawn. Looks quite messy after a while:
![shot0000](https://user-images.githubusercontent.com/84514074/167157507-031ed6cf-c4e8-420e-a179-f2c748e026c1.jpg)

_Originally posted by @3aTmE in https://github.com/PadWorld-Entertainment/worldofpadman/issues/153#issuecomment-1119707539_

**Comment by kai-li-wop** [comment]
This was discovered when testing the Screen Size slider (display menu page) in combination with the OpenGL2 renderer. The window background does not show the backtile texture, but the HOM effect. When using OpenGL1 this error does not occur. Ioquake3 shows the same error.

**Comment by ghost** [comment]
https://github.com/ioquake/ioq3/issues/304

**Comment by kai-li-wop** [comment]
@mgerhardy: Would you be able to provide a fix for this. It also could be applied to ioquake3. I am not able to fix it.

**Comment by mgerhardy** [comment]
it's about the image in `CG_TileClear` (`backtile.png`) - it's all properly written into the first pass color framebuffer - but not blitted into the screenbuffer.

**Comment by kai-li-wop** [comment]
@mgerhardy: There is a fix for this available in the ioquake3 main repo. Could you plz apply this. Thx
https://github.com/ioquake/ioq3/pull/621/commits/b111597debff11dea4827209c32c5c2d175f0d26
https://github.com/ioquake/ioq3/pull/621/commits/7f1bd9cd27d093bde0675de4b49433b5600f4ea8

**Comment by kai-li-wop** [comment]
Thx, should be fixed.

**Comment by 3aTmE** [comment]
Just tested it and confirm the fix! 👍
