### ISSUE TITLE
UI: Add OpenGL2 effects options to the menu

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#155]
ToDo
- [x] Add new menu page for effects options to system menu
- [x] Page is available only if OpenGL2 renderer is selected
- [x] Add High Dynamic Range (r_hdr): on/off (1/0)
- [x] Add Ambient Occlusion (r_ssao): on/off (1/0)
- [x] Add Auto Exposure (r_autoExposure): on/off (1/0)
- [x] Add Sun and Shadows (r_sunShadows): on/off (1/0)
- [x] Add Sunlight Mode (r_sunlightMode): Off/dynamic/Hybrid (0/1/2)
- [x] Add Filter Shadows (r_shadowFilter): Off/Default/Maximum (0/1/2)
- [x] Add Shadows Quality (r_shadowMapSize): Low/Medium/High/Maximum (512/1024/2048/4096)
- [x] Add Dynamic Light Mode (r_dlightMode):  Brightening/Light only/Light and Shadows (0/1/2)
- [x] Add Normal Mapping (r_normalMapping): on/off (1/0)
- [x] Add Specular Mapping (r_specularMapping): on/off (1/0)
- [x] Add Deluxe Mapping (r_deluxeMapping): on/off (1/0)
- [x] Add Parallax Mapping (r_parallaxMapping): on/off (1/0)
- [x] Add Sun Rays (r_drawsunrays): on(off (1/0)
- [x] Add proper tooltips for all new effects options

**Comment by 3aTmE** [comment]
Tried all options with the current a executable and recent codebase.
Worked without any issues! 

My only suggestion would be to add `/r_drawsunrays` just because they're looking neat :)

![shot0002](https://user-images.githubusercontent.com/84514074/168429383-b9e55046-1529-408d-8f91-8d4310117908.jpg)

**Comment by kai-li-wop** [comment]
Hmm, neat in fact. We are running out of space a little but I will see where I can place that.

**Comment by kai-li-wop** [comment]
With f46eda991d1f9667f3a698df712945ee08a522a9 I added the sun rays option to graphics effects menu page an realigned some of the other systems menu options. The switch is working but on my integrated Intel graphics sun rays are not shown to me somehow. However, the switch works. Closing this as implemented.
