### ISSUE TITLE
SERVER: Players using the third person mode will  set back automatically to first person view when the warmup timer finishes

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#156]
### The Issue:
When playing with the third person view enabled the player respawns automatically to the first person view _after_ the warmup timer finishes at the start of a match.

I know it's rather minor in nature. Just adding it here for the completion sake :)

### How to replicate:

1. Join a Server
2. Toggle to the third person view (default : I)
3. Start a new match per `/callvote map` or `/callvote map_restart`
4. Wait till the Warmup timer finishes 
5. You now respawn in the first person view instead of the third person one.

### Additional infos: 

**WOP Verison :** 1.6.2
**OS:** Windows 10

**Comment by kai-li-wop** [comment]
Additional Info: Third person view is bound to HOME and KP5 keys in WoP 1.7 dev.

**Comment by mgerhardy** [comment]
Looks like this happens in `CG_MapRestart` on purpose - this was at least part of the original quake3 arena source code release.

**Comment by mgerhardy** [comment]
Should be fixed now.

**Comment by 3aTmE** [comment]
I can confirm the fix!
