### ISSUE TITLE
Aiming does not take into account when the player is in third person view

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#157]
When aiming with Splasher and Injector, it is not taken into account if the player is in third-person view. In this case, he literally aims at himself. A solution would be to always automatically switch to the first-person perspective when zooming in and then back again. Any other options for a solution?

![shot0000](https://user-images.githubusercontent.com/44040989/167293868-df133e4c-2086-40b3-8581-3869389771d6.jpg)

**Comment by kai-li-wop** [comment]
We probably should also prevent the user to enable/disable third person view while scoping/zooming.

**Comment by 3aTmE** [comment]
I can confirm this issue as fixed.
I am not able to aim at myself while scoping.
