### ISSUE TITLE
UI: Game stutters for a bit when closing the Help / Gametype-Info / Pause menu while playing a single game

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#161]
### The issue: 

The Game stutters for a few seconds when i close the Help (Key: H), Gametype-Info (Key: G) or the Pause Menu (Key: ESC) while using a Executable build from the current codebase  (14.05.2022) and playing a _local single_ game. (Menu pauses the game)

This Issue appears on OpenGL1 as well on OpenGL2.

It's important to note that this issue _shouldn't_ occur while playing online or locally with multiple people!
So it's nothing that breaks but rather something odd I've noticed :)

### How to replicate ? 

- Make sure you've got the most recent code
- Make sure your executable is build from most recent code
- Start a game
- open the Help Menu (Key: H)
- close it
- The game should stutter for a few seconds before returning to the normal speed.
- Open a second instance of wop
- Join your Local game
- try it again. The issue should not occur.

### What have i tried so far? 
- Check if this Issue appears on OpenGL2, OpenGL1 or Both
- Check if this issue only appears only in windowed mode or also fullscreen
- crosscheck on my notebook if this issue also exist there. (It does, while less pronounced)
- Check if this issue only appears on a single local game or also on a local game with multiple clients

### Specs: 

**Desktop :**
- CPU : AMD Ryzen 5 3600
- RAM : 16GB  3000 mhz (Dual Channel)
- GPU : Radeon RX 580 8Gb
- OS : Win 10

**Notebook :**
- CPU : Intel Xeon E3-1505M v5
- RAM : 64 GB 2444 mhz (Quad Channel)
- GPU: Nvidia Quadro m2000m 4GB
- OS : Win 10

**WOP Version:**
Using the recent source & build of 14.05.22

**Comment by kai-li-wop** [comment]
> Using the recent source & build of 14.06.22

Wow, you managed time travelling. So we are going to implement this bug very soon and will fix it afterwards then. I am joking. ;)

Could be a sound related issue. Please also check for the re-choose spray logo and the team orders menu (F3). Is OpenAL or SDL enabled?

**Comment by 3aTmE** [comment]
> Could be a sound related issue. Please also check for the re-choose spray logo and the team orders menu (F3). Is OpenAL or SDL enabled?

Sorry that answering took so long. But this issue appears both on OpenAL and SDL.

> I tried to open the Team Orders menu but i just couldn't get it to work anymore. Even bound it to a different key. Still didn't work. (New Issue, hooray!)

Forget it. Everything works fine! I just was being stupid.
Oddly enough when using the team menu the stuttering won't appear at all.


> Wow, you managed time travelling. So we are going to implement this bug very soon and will fix it afterwards then...

Of course i can! Just... please don't tell anybody. Okay? Thanks!
In all seriousness tho, i just quietly fixed it :)

**Comment by kai-li-wop** [comment]
@3aTmE: Does this still appears with the current code base?

**Comment by 3aTmE** [comment]
@kai-li-wop Just tested it, nope! I can confirm this Issue as fixed! 👍

**Comment by kai-li-wop** [comment]
Whatever the issue was, no one fixed it. :D

**Comment by 3aTmE** [comment]
I don't mind stuff getting fixed by miracles or by otherworldly beings. As long the Issue goes away, i am always happy :)
