### ISSUE TITLE
Third person auto switch prevents the user from manually switching into third person mode

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#162]
I just re-discovered the CVAR cg_thirdPersonAutoSwitch which enables the user to switch from 1st person view into 3rd person view when ever the Punchy is selected and back, when he switches to another weapon. The downside of the currently implemented solution for this is, that it prevents the user to switch manually to 3rd person view and back when Punchy is not selected while cg_thirdPersonAutoSwitch is set to 1. The CVAR should only have an effect, if the user is not already in third person mode I guess.

**Comment by kai-li-wop** [comment]
Also, there is a menu option missing for this.

**Comment by kai-li-wop** [comment]
8833ddf91025971b839c9055f5eadd18047be805 removes this feature instead of fixing it.

**Comment by 3aTmE** [comment]
Wow! Never knew of the existence of this CVAR! 

Anyhow, i tested it in 1.6.2 first ,which obviously still worked and also broke my manual 3th person toggle.

Afterwards i tested it with the current code base. I was able to set this CVAR in the console, but it had no effect and my 3th person view toggle still worked. 

Or to keep it short: I can confirm this as working :)
