### ISSUE TITLE
FREEZETAG: Boaster water stream shown while frozen

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#164]
Currently it is possible to shoot with the BOASTER while the player is frozen in Freeze Tag. Pressing the attack button draws the water jet and is shown to the player, but it doesn't do any damage. I haven't tested the third-person view yet. Shooting with weapons should be completely disabled in the frozen state.
![shot0000](https://user-images.githubusercontent.com/44040989/171196227-76986bfb-4cf3-499c-be13-f1b5355fc250.jpg)

**Comment by mgerhardy** [comment]
Should be fixed - double checking would be nice.

**Comment by kai-li-wop** [comment]
The issue seems to be "half" fixed. I cannot see the water jet any more but I can still hear the flash sound while firing. I don't know if it is connected but I can remember a similar issue with spectator mode. When people in LPS died and went to spectator with boaster selected, they could still fire the boaster without being equipped with boaster and without causing damage. Seems to me that the water jet is not coded in a good way. I found yesterday a comment regarding a solution for this in cg_weapons.c line 915. It maybe helps.

**Comment by 3aTmE** [comment]
>  ....I cannot see the water jet any more but I can still hear the flash sound while firing....

Just tried it for myself. I can Confirm this behaviour

**Comment by kai-li-wop** [comment]
Found a way to stop the flash sound while carrying the BOASTER in frozen state client side. This fixes the issue for me but I don't now if it breaks other stuff. Looking at @mgerhardy for approval. ;)

**Comment by mgerhardy** [comment]
It works like that - but a better fix would be to remove the `EF_FIRING` event on the server side. I've tried a few things there already, but nothing really works - so let's call it done for now, as this is also already used in other situations to be filtered client-side.

**Comment by 3aTmE** [comment]
Just tried a quick match with the recent codebase.

While i can't add anything to the technical discussion, at very least i can confirm the fix as working ! 👍
