### ISSUE TITLE
Distribution: Snap Store / Gnome Software

### ISSUE THREAD

**Issue by digidigital** [PadWorld-Entertainment/worldofpadman#164]
I have tried snapping the game (1.6.1) and it was the easiest snap I ever made :)
The base game seems to work almost "out of the box". 

You would be able to install it from the snap store and start it from your desktop / app launcher like any other software.

Since snaps run in a restricted environment you can not drop custom maps / mods / models in the wop-folder.
Instead you have to put them in the ~/snap/wop/current/.padman/wop folder. Since this folder is versioned you have to copy the custom files to the next "current" folder after each update. This somewhat contradicts the idea of simplifying the installation and general handling.

Another approach could be to write a small Padman-Installer/Launcher GUI that downloads and installs the game in a persistent and writable folder -> SNAP_COMMON.  I have not tested if you can execute files in that folder, yet.  
If it is working adding / removing additional content could be done in this application as well.
In this case we would need a reliable server that hosts the game files without captchas or token links (or grab the token links from the website). 

From your perspective, is it at all desirable to have the game in the Snap Store? Any license issues?

**Comment by digidigital** [comment]
Another (yet untested) option could be: 
- pack the base game content into the snap (no separate download server for game files needed)
- add launcher script that checks if pk3s are in the non-versioned writable space and symlinks them to ~/snap/wop/current/.padman/wop before the game is started if the pk3s are not already symlinked 
- add a small management gui (to the launcher or as separate application) that enables the user to manage (copy to / delete) files in the writable directory.

**Comment by digidigital** [comment]
I did some tests:
- SNAP with Core20 and GNOME-3-38 extension since glibc > 2.29 is needed
- Set HOME to $SNAP_USER_COMMON (writeable, no versioning/backups for Snap updates)
-  audio-record plug (prvileges to record audio) needs to be manually switched on in the snap store gui / software settings 
- I made a small "File Manager" that you can use to copy .pk3-files and .cfg-files in the correct folder (need to ask for ENTE's approval for putting Padman in it).

![Bildschirmfoto von 2021-09-22 10-19-20](https://user-images.githubusercontent.com/28964886/134308170-c6692dcb-2a1a-4736-9ce1-cbc8a96e6a40.png)

File size is 1.1G so I need to check if there is a size limit for snaps.

**Comment by digidigital** [comment]
1.1GB is fine on the snap store :)

Uploaded to beta channel and set to private until I get an approval...

If you prefer an official snap publisher account I can provide you with the snapped game / snapcraft.yaml needed to build the package.

Store Desktop Application:
![Bildschirmfoto von 2021-09-24 19-02-08](https://user-images.githubusercontent.com/28964886/134713516-5ea486f8-5844-40e5-9256-188c1be83a28.png)

Store  website:
![Bildschirmfoto von 2021-09-24 18-54-43](https://user-images.githubusercontent.com/28964886/134713033-2f1d6c7e-c714-41c5-ad4b-2028aa76add5.png)

**Comment by kai-li-wop** [comment]
Hi. Thank you for putting so much effort into this. We really appreciate it and it looks very good. Once WoP 1.6.1 is released as final, I would like to ask you to update the content to the final version. I don't see any licence issues, as WoP clearly states that it can be distributed freely for non-commercial purposes. Would it possible also as WoP team to get access to this distribution system, simply for the possibility to do minor changes in descriptions or to update the files in future?

**Comment by mgerhardy** [comment]
Yes, the snapcraft.yml would be great - we plan to automate all these steps and especially the release packaging into ci pipelines.

**Comment by digidigital** [comment]
@kai-li-wop : I suggest to create an official Ubuntu One account with a worldofpadman.net e-mail address (either you create it and share the credentials with me or you can forward the address to my e-mail address and I take care of it) then you have full control of the listing and build pipeline. Once the automation - as planned by @mgerhardy - works I am not needed anymore :)

@mgerhardy : Currently I just dump the game files from the official download into the snap package. This circumvents some steps that might cause serious headaches :) 
[snapcraft.yaml.txt](https://github.com/PadWorld-Entertainment/worldofpadman/files/7479158/snapcraft.yaml.txt) (I had to add .txt since you can't upload .yaml files...)
Alternatively we can try to use the automation features already available in snapcraft. I have never used it with C applications but the basic steps consist of:
1. Create a snapcraft folder in the root of the github project
2. Create a snapcraft.yaml in this folder with build/packaging instructions
3. Whenever there is a commit to the the main branch a build is triggered 
4. If the build is completed without errors it is automatically published to the store as "latest/edge" version
5. You can manually promote the build to "latest/candidate" "latest/beta" or finally to "latest/stable" 

The tricky part is step 2 since you have to list all dependencies needed to build the binaries and make sure make / make install works correctly in the build environment which is a more or less "basic" Ubuntu image. As long as all dependencies and libraries are available in the right versions via apt or can be downloaded as binaries we are fine once everything is listed as "build dependency". If you have to build the dependencies yourself and they need other dependencies this can lead to a frustrating situation...    
Since the media files (artwork, maps etc.) are not part of the repository we need to download them somewhere and dump them in the right place a) via public download from some server or  b) via a separate "media snap" that can be passed as a dependency for staging (I never did this before). The cool thing is  - once everything works fine it's a dream :)

I can try building a snap package with the snap "make"-plugin over the weekend. Since I am more of a Python guy I am sure I come back to you with some questions in case of build errors :)

**Comment by digidigital** [comment]
Good news! It seems I am able to compile the binaries.
Maybe I have something to show you tomorrow...

**Comment by digidigital** [comment]
@mgerhardy , @kai-li-wop It seems It seems I have covered the basic steps as mentioned above. 
All dependecies for building and running wop are in place and wop can find them at runtime, build (x86_64) works fine.
media files from separate zip are copied in the right place as well. 

BUT -> something I might have asked earlier -> I assume I have to  update the vm files in wop_007.pk3 and / or wop_006.pk3 right? Doesn't this brake the check for "pure"-files?   If this can only be avoided by centrally compiling the files for distribution, the first approach should be chosen, where the universal zip is simply copied into the snap.
I assume this can be scripted in a build / packaging environment as well by automating the snap compilation and via token based snap update upload.

So I need a bit of input regarding this issue... :(

**Comment by kai-li-wop** [comment]
You are of course right, the qvms are part of a PK3 file and would have to be packed accordingly. If you create another wop_007.pk3 than the "original" it comes to the problem described by you. I would suggest that the automation is not done until WoP 1.7, since we will probably do away with QVMs with that version. However, this has not yet been finally decided! Also, the assets will move to the worldofpadman repo, which should simplify things then. Therefore, it is probably enough for now, if the files are dumped in manually as in your first approach. I lack a bit of time at the moment to deal more deeply with the matter. I assume that @mgerhardy will take a closer look at the matter.

**Comment by digidigital** [comment]
@kai-li-wop : Okay - I have published the snap @ https://snapcraft.io/worldofpadman in the beta channel. I have crated a whole new Ubuntu One / Snapcraft account that I can pass on to you guys anytime you like. You should have received an invite by snapcraft.io since I have added you as "collaborator" (whatever exactly that means) ->  "You can collaborate with others administering this snap by listing recipients directly."

When I have cleaned up the automation-snapcraft.yaml I'll post it here for reference.

**Comment by kai-li-wop** [comment]
@digidigital: I received your invitation email thx. Meanwhile WoP 1.6.1 is officially out. Would be good to update the snap to the latest "stable" release. I will have a look into the snapstore ans soon as I can to update some descriptions and pictures. Meanwhile feel free to use material from the website. When this is done, I will post a news about the snap.

**Comment by pizzadude** [comment]
Hi, I tested the snap in Fedora 35 KDE wayland and it works fine.
