### ISSUE TITLE
UI: 1.6 clients have a broken Player menu when downloading wop_007.pk3 shipped with WoP 1.6.1

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#165]
I didn't notice this before in all the weeks of testing but it's true. If an old 1.6 client gets the wop_007.pk3 from somewhere, the player menu breaks. It looks like the user can no longer select a model and the skin icons are no longer displayed. Perhaps it has to do with the fact that the old client does not support PNGs, although I'm not really sure about that. Thanks to Ben for pointing this to me.

![shot0016](https://user-images.githubusercontent.com/44040989/139543778-c9357fc5-af7a-460b-b320-4efe9ddada67.jpg)

**Comment by mgerhardy** [comment]
Yes, the binary of wop is still 1.6 - only qvms are downloaded. But the engine is not the up-to-date version that uses the latest ioq3.

**Comment by kai-li-wop** [comment]
It looks to me like it's related to issue #87 when the changes corrupted the custom player models with png icons. I know we tried to enable png icons for the player menu, but I don't know how that is related to the engine. The goal of WoP 1.6.1 was to provide an engine update and new qvms, but not break compatibility with old 1.6 clients. It should be possible to play on 1.6.1 servers with a 1.6 client using only wop_007.pk3, otherwise we would have to increase the net protocol number to avoid such incompatibilities. But I don't want to do that before WoP 1.7.
If this is the only problem now, then I would rather wait with the PNG support and publish these changes only with WoP 1.7. Then we have all the freedom to break with previous versions. Of course, I don't know how much work it would take to revert these changes to png support if that is really the cause. Maybe it is connected to the tga png order changes.

**Comment by kai-li-wop** [comment]
This error is not removed, because this state can only be achieved by half an update. It is recommended not to distribute the wop_007.pk3 file through the servers, because this way the new binaries cannot be loaded automatically. The update should therefore be done manually by the user and thus also completely.
