### ISSUE TITLE
Gametype: Catch The Killerduck

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#167]
**Catch The Killerduck** for World of Padman can be a new and interesting game type. The idea goes back to a list of ENTE's originally planned game types for World of Padman. Besides **Spray Your Color** and **Last Pad Standing** ENTE also planned to implement **Catch The Baby** as an unique game type for WoP. A player randomly would turn into an ugly baby  that runs through levels trying to survive while other try to frag it. Points are given for every second of surviving as a baby. This idea is also based on [Catch The Chicken known from Quake 2](https://web.archive.org/web/20000817003915/http://www.planetquake.com/chicken/), but here a player holds the chicken while remaining a normal player. This idea was also adopted for [Quake 3 Arena additionally featuring a team mode](https://openarena.fandom.com/wiki/ModCompat/Q3_Catch_the_Chicken) but the source code is not available. See the [video](https://youtu.be/b0RIB6th91M) for some impressions.

For a possible implementation in WoP we should drop the idea with the baby and go for a Killerduck instead. A player should hold one instead of turning into one (easier to implement). The gameplay remains the same. The Killerduck spawns at the spot of the holdable and can be picked up by the players. If the Killerduck is dropped it is removed from the map after 5 seconds and randomly respawns at player spawn points for players to collect. In this case we don't run into issues like the Catch The Chicken mod where the chicken was placed randomly on the map and sometimes not reachable for players.

All players are invulnerable except for the one who carries the Killerduck. His task is to dodge the attacks of the other players and to survive as long as possible. The longer he survives, the more points he gets. ~~As his only "defense", the Killerduck he carries leaves puddles of oil from time to time for the attackers to slide around on, but it also draws a trail for the attackers to find the carrier.~~ The points received are displayed via a score plum that is visible through walls to also draw a trail for attackers to find the wearer faster. If you get tired of running around carrying the Killerduck, you can drop it. The carrier also should be highlighted like a lolly carrier in CTL.

The Killerduck carrier should start with 200 points each for health and armor. The quacking and squeaking of the Killerduck should be audible. Perhaps the Killerduck carrier should also be a bit faster than his hunters (130%).

ToDo:
- [x] Establish "Catch The Killerduck", "CTKD", "GT_CATCH" menus and voting, enable support for all FFA maps
- [x] Spawn the Killerduck at the spawn point of the holdable as usual
- [x] Player starts with 200 health and 200 armor and is vulnerable when collecting the Killerduck
- [x] Payer should drop all other holdables when collecting the Killerduck
- [x] Killerduck carrier drops the Killerduck when dead
- [x] Killerduck carrier should be able to drop the Killerduck by using the drop item key (not the use key)
- [x] Respawn the Killerduck holdable model at player spawn points if not picked up after 5 seconds after dropped by a player
- [x] Also a respawn at the original Killerduck spawn point should be possible
- [x] Normal players hunting the Killerduck carrier are invulnerable
- [x] Put the Killerduck model in the hand of the carrier
- [x] Killerduck should quack, squeak ~~and be animated while being held~~
- [x] Killerduck carrier should be highlighted with golden circular aura (like in CTL when carrying a lolly)
- [x] Killerduck carrier should be highlighted in the scoreboard by Killerduck icon or model
- [x] Killerduck carrier should be faster as other players (130%)
- [x] Killerduck carrier should jump higher as other players (150%)
- [x] Killerduck carrier should score points for every 3 seconds of survival, show score plum visible through walls
- [x] Killerduck carrier should not be able to collect weapons and ammunition
- [x] Add game type help and info screen infos
- [x] Make the bots understand to collect the Killerduck as a first goal
- [x] Make the bots to hunt the Killerduck carrier instead of shooting each other
- [x] Make the bots run away from other players when holding the Killerduck instead of looking for items
- [x] Show a wallhack hint icon above the Killerduck holdable when available to be picked up somewhere in the map and add a menu option for this

**Comment by kai-li-wop** [comment]
@mgerhardy: The game mode works quite well now even with bots. After a longer game session yesterday, however, I noticed that the current handling of how the Killerduck spawns is somewhat demotivating. If you have killed the Killerduck carrier, the reward for collecting the Killerduck is missing, because it is not dropped by the carrier, but spawns somewhere in the map. It also lacks the visual feedback and orientation of where to find the Killerduck. A better strategy would be not to chase the carrier, but to wait somewhere at a higher point in the map, so that after the kill of the carrier by another player, the respawning Killerduck can be spotted and picked up as quickly as possible. In any case, the player who has killed the carrier is not rewarded. Usually someone else gets to the Killerduck faster. Therefore I have the following suggestions:

- The Killerduck carrier should drop the Killerduck on the spot after he is shot, so that it can be picked up directly by the opponent.
- If the carrier wants to drop the Killerduck on purpose, the visual feedback is also missing so far. Therefore, the Killerduck should be droppable like a lolly or a cartridge via the drop item key and visually drop in front of the player.
- In any case, if the Killerduck is not picked up within 5(?) seconds after it is dropped by a player, it respawns automatically at a player spawn point as before. This also prevents it from accidentally dropping to an unreachable location.
- The use of the drop item key instead of the use key is then also coherent with the other game types. The Killerduck is not fired in CTKD, but only dropped.

Apart from this, the game type is really fun and challenging even with bots. Looking forward to release it with a beta.

**Comment by 3aTmE** [comment]
I played it for a bit and had some Fun with Bots! 

As far i can tell this game mode works really well. 

One thing that just confused me at first that i was not able to pick up the Killerduck when carrying holdables like Floater.

Maybe a text prompt like "You need get rid of the Floater First" or just keeping the floater out of this game mode entirely could help in these cases.

Anyways, this is really an fun addition and i can't wait to test it with other people online!

**Comment by mgerhardy** [comment]
That's a good point, maybe we should drop the other holdables first before becoming the killerduck.

**Comment by kai-li-wop** [comment]
Simply to drop any other holdable when picking up the Killerduck, yes.

**Comment by kai-li-wop** [comment]
@mgerhardy: Two more suggestions:

1. a respawn at the original Killerduck spawn point should be possible
2. maybe the Killerduck carrier should not be able to collect weapons and ammunition, usually the hunters are after him and quickly run out of firepower if the carrier collects them all right in front of them

**Comment by kai-li-wop** [comment]
@mgerhardy: Would be good to finish finish those last open aspects.

**Comment by 3aTmE** [comment]
Just tested this game mode again! ~The new changes made worked so far without issues.~  See the "What was tested" section 😁 

The only issue I've encountered so far is the one described in #224 . 
Funnily enough, after collecting the second killerduck , then losing it would stop re-spawning one of them. You end also with one collectable killerduck again.

### What was tested ? 
- Being able to collect ammo and weapons while holding the killerduck ( was unable to )
- Collect powerups ( like expected every powerup worked as they should expect for other holdables) 
- Collect the killerduck while carrying the floater ( or other holdables) 
- - Was able to collect the killerduck. My floater gets dropped like it should. But i am not able to collect points by doing so. My speed won't also not increase and i am still holding my weapons. I am also still able to collect weapons and ammo. But i can't collect other holdables ( like floater) anymore. Creating a new issue for it. 
- - **EDIT :** I was not able to recreate this issue. I don't know what caused it in the first place.
