### ISSUE TITLE
Unification of the player sprites appearance and handling

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#168]
The player sprites that are displayed above the players' heads are currently treated and presented differently.

There are 7 wallhack icon options available in the options/help (preferences) menu: teammates, health stations, SYC teleporter, BB boxes, LPS arrow, frozen teammates, killerduck. Options and tooltips are not always accurate on what the switches do right now.
- Switches for health stations, SYC teleporter, BB boxes, and Killerduck enable/disable the icons for those game objects in the respective game types. Enabled means here displayed and visible through walls with scaling function.
- Switch for LPS arrow enables/disables the whole icon for the LPS arrow player sprites (blue/red). Enabled means displayed and visible through walls with scaling function.
- Switches for teammates and frozen teammates handle things differently. They simply enable/disable, if the icons are visible through walls or not. They do not scale in general. They don't handle if the icons display is enabled/disabled in general. For the teammate icon there is also CVAR cg_drawFriend for this but not bound to the menu.

ToDo or to discuss:
- [x] The frozen teammate icon should behave like the LPS icons by using the scaling function and visible through walls. Like with the LPS icon the frozen teammate icon should reveal frozen teammates from any position of the map.
- [x] The teammate/friend icon should also appear like the LPS icons by using the scaling function and visible through walls. The menu option under wallhack only should enable/disable the scaling and wallhack feature.
- [x] A new option teammate/friend icon above the wallhack section should enable/disable, if the icon is shown at all. If disabled, it should also gray (disable) the wallhack icon option in the menu. This should be controlled by the given CVAR cg_drawFriend.
- [x] The wallhack flag of the teammate/friend icon should also apply to all team game modes to make it visible through walls in all team game modes, not just Big Balloon.
- [x] Change order of menu items according to their target: a game object or the player. We should distinguish between them and not to mix their menu entries.

**Comment by kai-li-wop** [comment]
See 5d5081277b89efb88f38aa9534b71979a13b2e83 for changes regarding wallhack icons.

**Comment by 3aTmE** [comment]
Just tested changes made regarding the team mate icons and can so far report that everything works as it should! 

**What was tested? :**

- Frozen Team mate icons behaving like LPS Icons
- Team icons behaving like LPS Icons
- Toggling "Teammate Icons"  on / off grey out "Teammate/Friend" in the Options
- Other icons in different game modes behaving according the changes made
