### ISSUE TITLE
Better hit sound feedback for the players

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#169]
Quake 3 Team Arena supports different hit sounds, depending on the shield and health points of the attacked player. This feature can also give the attacker in WoP a direct and better feedback about the health and shield condition of the attacked player. For this purpose, the existing hit sound is supplemented with two additional hit sounds:
- Shield > 50: Hit sound high shield
- Shield > 0 OR Health > 100: Hit sound low shield
- Otherwise: default hit sound

For further implementation, the existing default hit sound would have to be adjusted in frequency. The default hit sound could also deviate from it to sound more "fleshy". The feature should be additionally switchable via a new CVAR "cg_advhitsounds".
- cg_advhitsounds 0: off (default hit sound)
- cg_advhitsounds 1: on (extended hit sounds)

In addition, the team hitsound should better indicate that here the player is shooting at his teammate. An additional announcement by the announcer would also be conceivable here.
- "Watch your fire!"
- "Cease fire!"
- "Friendly Fire!"

**Comment by 3aTmE** [comment]
+1 for this addition!
[I've experimented a while back with an simple Beep Sound ](https://youtu.be/b5sXRq3AB1Y) as an audio feedback for hits. Felt immediately more satisfying to hit stuff! 

Looking forward to test this! :)

**Comment by kai-li-wop** [comment]
Ah, I remember this. Such a beep sound sample would be suitable in friendly fire situation. I like it. From where did you get it?

**Comment by 3aTmE** [comment]
[Quickly Made from scratch with bfxr ](https://www.bfxr.net/) :)

Quite a handy tool if you need to generate sounds fast.

A far superior alternative to this is labchirp.

**Comment by kai-li-wop** [comment]
Replaced by pull request #176. Any further comments should go there.
