### ISSUE TITLE
Restore and enhance the player event "holy shit"

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#172]
The player event 'holy shit' is deactivated in World of Padman and the code has been partially removed. Holy shit is called out when a player with a flag is immediately intercepted in front the opponent's flag and can no longer score. It should be reintroduced, but in a weakened form. The announcer should say something nice with astonishment here, e.g. "Wow, that was close!" or "Almost captured!" Also the existing "Better luck next time, maybe!" from LPS seems suitable. This could add more dynamics to the game. 

ToDo
- [x] Check for possible "16bits limit" issue (also connected to #15) --> no issue here!
- [x] Restore the code for "holy shit" (used in CTL) --> renamed to "almost capture"
- [x] Apply the event on SYC for failing to enter the teleporter with cartridges (>=5)
- [x] Apply the event on BB for failing to raise the third balloon to receive Big Balloon (4a9e91cb80972f41a832d4eb2dac90a0e4b9453e)
- [ ] _Optional: Provide announcer sound sample "Wow, that was close!"_

**Comment by kai-li-wop** [comment]
02d9ff3174a613371ece30c6e9be139eb80e785a restores the "holy shit" player event which works nice and is not annoying in my point of view. Was removed probably because of language but is replaced now as "almost capture" everywhere. Plays "better luck next time, maybe" which I find suitable for this (was used only in LPS before). So probably we don't need a new sound file for this.

**Comment by kai-li-wop** [comment]
Should work now also with SYC and SYC Team. Still not working with BB.

**Comment by kai-li-wop** [comment]
Should also work now for BB when failing to capture the last balloon to receive BigBalloon

**Comment by 3aTmE** [comment]
Just tried this feature locally :

**SYC &  SYC TEAM**
> Works! Could trigger the player event flawlessly.

**BB**
>  Works! Could trigger the player event flawlessly.

**CTL**
>  Works! Could trigger the player event flawlessly.

So yeah, i can confirm that this feature works fine!
