### ISSUE TITLE
UI: WoP has no flags but lollies, team names should be adjusted and there is no lead in WoP

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#172]
A minor imperfection that I just noticed. WoP has no flags but lollies, the should be in the status messages also nothing about flags (see screenshot): "Hectic fragged RED's flag carrier!"

Also, the team names are "RED PADS" and "BLUE NOSES" and not just RED and BLUE as I recall. Maybe this has never been implemented properly, but we should do it uniformly sometime.

Finally, there is to say that in WoP you can not pump anyone full of lead, because the pumper does not shoot lead. Smiley had already noted that correctly. The players are electro-shocked or get get electrocuted by the pumper (see screenshot): "Adri{HUN} was electrocuted by rikaki's Pumper"

![shot0030](https://user-images.githubusercontent.com/44040989/140661409-d82a242a-f2d0-46c1-99fc-30277207d485.jpg)

![shot0033](https://user-images.githubusercontent.com/44040989/140661573-f4daa206-745d-4a9f-a636-74bffb2c491f.jpg)

**Comment by kai-li-wop** [comment]
- [ ] Replace "... fragged RED's flag carrier!" with "... fragged RED's lolly carrier!"
- [ ] Rename team names to "RED PADS" and "BLUE NOSES"
- [ ] Replace "... was pumped full of lead by ... Pumper" with "... was electrocuted by ... Pumper"

**Comment by mgerhardy** [comment]
Should be fixed now.

**Comment by kai-li-wop** [comment]
I have one more small note, because I think that here the new team names have not yet been implemented completely correctly. I'm not an English professional but since the two team names now end on s, there should be at least one apostrophe in the genitive instead of 's before.

should be like this I think
... captured BLUE's lolly carrier --> ... captured BLUE NOSES' lolly carrier
... captured REDS's lolly carrier --> ... captured RED PADS' lolly carrier

currently it is solved without apostrophe
... captured BLUE's lolly carrier --> ... captured BLUE NOSES lolly carrier
... captured REDS's lolly carrier --> ... captured RED PADS lolly carrier

**Comment by kai-li-wop** [comment]
I also have seen other messages without apostrophe like '... returned RED PADS lolly. So there are more messages such a like. But I have also seen others with correct apostrophe behind RED PADS in CTL.

**Comment by kai-li-wop** [comment]
Should finally be fixed with https://github.com/PadWorld-Entertainment/worldofpadman/commit/24e2e01fa404e96b42e41a4179fa4cb77709b4d4
