### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by AsciiWolf** [PadWorld-Entertainment/worldofpadman#178]
It would be great if World of Padman was packaged as a [Flatpak](https://flatpak.org) and distributed on [Flathub](https://flathub.org). It would bring new players to this great game since Flathub support is present out-of-box on many modern Linux distributions including Valve SteamOS.

**Comment by AsciiWolf** [comment]
So, I started working on the Flatpak myself. However, I have two questions:

1. Is it fine to redistribute the game data files (pk3s) with the Flatpak (in the Flathub.org repository)? If I read [the WoP license](https://worldofpadman.net/en/about/copyright/) correctly, it is, however I would like to see this confirmed directly from a PadWorld Entertainment member.
2. Are you interested in co-maintaining the WoP Flatpak (push rights to its Git repository) after it is accepted and published on Flathub?

Thanks! :-)

/cc @mgerhardy @kai-li-wop

**Comment by kai-li-wop** [comment]
Hi there, I have recognized your posting but had no capacity to answer it or to have a closer look at flathub. I appriciate your commitment. I would consider flathub then with an upcoming release of WoP. Regarding the license, The distribution of WoP is free, if it is without commercial interest and no money is made. I can take some time during the upcoming days to have a look at flathub but right now it is Christmas and I enjoy spending time with my family. 😉

**Comment by kai-li-wop** [comment]
Oh an I forgot to mention the WoP is already distributed via Snap Store, which also was initiatet by the community.

**Comment by AsciiWolf** [comment]
Nice, thanks! :-) I have finished the Flatpak and it seems to work fine except one issue that I will hopefully be able to fix. I will submit it as a Pull Request to Flathub, but will wait for your review before marking it as ready. :-)

Have a wonderful Christmas!

Regards,
Daniel

**Comment by AsciiWolf** [comment]
https://github.com/flathub/flathub/pull/3754 - Feel free to review. :-)

**Comment by AsciiWolf** [comment]
The Flatpak was accepted and should be live on Flathub in a few hours. :-) Feel free to comment in the linked PR or this ticket if you have any further comments or if you are interested in push permissions to the [WoP Flatpak repository](https://github.com/flathub/net.worldofpadman.WoP).

**Comment by kai-li-wop** [comment]
I am sorry for not being able to review this because I am traveling outbound until mid of january. But as I understand it, you referenced the unified zip from hectic's zock server which is ok. I was afraid you referenced the unfinished development branch, which is the main branch of our repo. Anyways, I will have a closer look when I am back. This needs to be maintained properly whith new versions of WoP being released then. But thanks for your Initial work.
