### ISSUE TITLE
Can't launch after compiling: "LoadTGA: Only type 2 (RGB), 3 (gray), and 10 (RGB) TGA images supported."

### ISSUE THREAD

**Issue by syghfy** [PadWorld-Entertainment/worldofpadman#179]
OS: Manjaro Linux

built with "make -si"

[crashlog](https://github.com/PadWorld-Entertainment/worldofpadman/files/10329408/crashlog.txt)

**Comment by mgerhardy** [comment]
You need git-lfs installed when cloning the repository. If this isn’t the problem, please re-open the issue

**Comment by kai-li-wop** [comment]
Reminder to myself: update the compiling tutorial with a hint regarding git-lfs! https://worldofpadman.net/tutorials/compiling-wop-with-cmake-in-vs-code/
