### ISSUE TITLE
Support of individual sounds for player model skins

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#18]
WoP should support an individual taunt sound sample for a player model skin, i.e. StonePad could have a different taunt sound than PADMAN. It could be implemented in the same way as the individual head models for player skins. If no individual sound file of a skin is available, the default sound file of the model should be used, i.e. PADMAN instead of StonePad. Eventually we could extend this to all model sound files. Suggestion for naming scheme:

Padman (model) | StonePad (skin)
--- | ---
death1 |  death1_stonepad
death2 | death2_stonepad
death3 | death3_stonepad
drown | drown_stonepad
fall1 | fall1_stonepad
falling1 | falling1_stonepad
gasp | gasp_stonepad
hehe1 | hehe1_stonepad
hehe2 | hehe2_stonepad
jump1 | jump1_stonepad
pain100_1 | pain100_1_stonepad
pain25_1 | pain25_1_stonepad
pain50_1 | pain50_1_stonepad
pain75_1 | pain75_1_stonepad
taunt | taunt_stonepad

**Comment by kai-li-wop** [comment]
Due to the simpler implementation, in contrast to the description above, since a59906fe63e3b6a8d14acf8030629066884f6942 a complete sound set for a skin can be stored in parallel to the folders of the models. Example:

Skin: sounds/wop_players/padbabe/...
Model: sounds/wop_players/padgirl/...

The code first takes the sound files from the skin folder and takes the files from the matching model folder as fallback if an error occurs. This was easier to implement. Currently the console still gives many warnings, which is unnecessary in this case. To test this feature chose PadBabe instead of PadGirl which should play a different gesture sound.

**Comment by kai-li-wop** [comment]
With ddaa373b82d61a2f9713f6bffbde21dd2e71b45d I added for testing purposes two more alternative gesture sounds from the original PADMAN model which I found suitable for PadSoldier and SuperPad. We need new gesture sounds recorded by ENTE here.

You can test now with:
- PadBabe
- PadSoldier
- SuperPad

**Comment by 3aTmE** [comment]
Just tried it out.

Works just fine. Nothing else to report here :) 

- **PadBabe**
Normal, Blue and Red variant : Works without any problems "Don't call me Babe" soundfile plays as indented
- **PadSoldier**
Normal, Blue and Red variant : Works without any problems "Nice to frag you!" soundfile plays as indented
- **SuperPad**
Normal, Blue and Red variant : Works without any problems "Nobody can stop me!" soundfile plays as indented
