### ISSUE TITLE
MAP: No clipping on the Bananas on wop_fridgeCTL

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#180]
# The Issue :

On _both_ bases on `wop_fridgeCTL`  the Clipping is missing on the Banana under the Choclate (see screenshot)

![shot0001](https://user-images.githubusercontent.com/84514074/210250762-ba9cd783-3c90-4e15-b5cd-55a1ea05ddba.jpg)

# How to replicate :

- Start an local CTL game  on `wop_fridgeCTL`
- Go to the lower shelf in any base.
- Try to crouch under the banana. You should able to crouch through it.

# Tested on: 

World of Padman 1.6.2 
while playing on the PadWorld Server

**Comment by kai-li-wop** [comment]
Should be fixed with 43a9efc92c7252109ebc3b0047c8cd16c9ffc224.

**Comment by 3aTmE** [comment]
Just tested it, i can confirm the fix ! 👍
