### ISSUE TITLE
Colored balloon HUD icon in game mode Big Balloon visible through walls

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#187]
In Big Balloon, the balloon HUD icon is displayed above a player's head instead of the PadStar medal when a balloon is captured. The balloon icon is colored by the code depending on the team color and is displayed above the player's head for a short time, causing the balloon icon to be visible through walls. For icons not to be visible through walls, a shader is needed. However, this shader prevents the icon from being colored by the code. This results in the player's position being visible throughout the level for a certain amount of time. There are several solutions to fix this problem:

1. the balloon icon should not be colored by the code, but instead a red and blue balloon icon should be added with shaders.
2. the balloon icon can also be replaced by the PadStar medal, which would result in the same behavior as in CTL.

**Comment by kai-li-wop** [comment]
6eef48eac0d5b25b8bbfef41a4e5ccb20f4fb16e should fix the issue by applying 2nd solution;
- Adds a RED PadStar medal to the game in CTL and BB
- Applies to RED team players when PadStar is shown as award and as player sprite
- Old medal applies to the BLUE team

**Comment by 3aTmE** [comment]
Just played an match on `wop_trashmapBB`and can confirm the fix.

The Icon won't be visible through walls and each team got hier right color when capturing the balloon.
