### ISSUE TITLE
UI: Optimization of the model and skin selection in player settings menu 

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#190]
The selection of a player model with a corresponding skin requires a lot of clicks and especially with Padman with currently 27 available skins (incl. color variants) it is hard to keep track.

- [x] The arrows in the lists of models (left/right) and skins ( up/down) should indicate the beginning and end of the respective list by being grayed out (same bahavior like all the other list arrows in the menus)
- [x] If there are less than 4 models or 3 skins for a model, the arrows should no longer be displayed (hide them)
- [x] The arrows in the list of skins for each model should always switch 3 skins back and forth, instead of just 1; this will reduce a lot of unnecessary clicking (page view approach)
- [x] In order to reduce further endless clicking up and down through the skins, the team colors should no longer be displayed on the right side of the menu with icons
- [x] The skin color selection (default, blue, red) should be controlled by a separate menu item on the left and should be retained when the model or skin is changed by clicking other icons
- [x]  The label under the player model should only show the model or skin name without indicating the color (_blue/_red), which is well indicated by the new menu item

Further thoughts
- The space in the menu on the left is a bit limited. If the widescreen menu can still be implemented, there will be more space available there
- It would be good to generally implement a pagination approach for model and skin lists to make navigation with arrows in the code much easier to handle which also avoids existing problems with the models list code

Current state of implementation:
![shot0003](https://user-images.githubusercontent.com/44040989/221631797-e9aa9659-bd23-4a1d-85dc-05c26a842eed.png)

**Comment by kai-li-wop** [comment]
@mgerhardy: There are still issues in `UI_PlayerSettings_Update`. The second condition `if (s_playersettings.chosenskins[0] < SKINSPERPAGE)` does not seem to work properly. In the current model constellation the code seems to work fine, but if a model with more than 3 skins is added further down the menu, the arrows (skin up/down) are not displayed, but should be. Maybe s_playersettings.chosenskins[0] is not the right condition at this point. Actually, it should check if the number of skins (without color variants) for the selected model is less than or equal to SKINSPERPAGE (=3), then the arrows should be hidden.

**Comment by kai-li-wop** [comment]
The issue is fixed and the enhancement should work like expected. It could cause some issues when custom model skins do not align to the default naming scheme (default, red, blue, _red, _blue) at the end of the file name.

**Comment by 3aTmE** [comment]
After Testing with the recent Codebase everything seems to work like it should. 

What i haven't tried yet is to use custom models or skins.

But what is the Sex Option doing? 

I guessed first that it will change the pronouns in the frag messages Like "PadPlayer blew themselves up" for None but nope.

**Comment by kai-li-wop** [comment]
The skin selection option is probably not always working with custom models and will probably be reverted with the introduction of the wide screen menu. There will be more skin Icons shown, so default, red and blues skins can be selected more easy.

The gender selection option is still without influence but in fact the idea is like you assumed. With this option the user should be able to overwrite the gender given by the selected model in future.
