### ISSUE TITLE
FREEZETAG: Icy and snowy weapon effects

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#191]
The original XMAS mod uses some alternative weapon effects for the Freeze Tag game type. While most of the game type features are already implemented, these alternative weapon effects are still missing, as are some new things to be implemented. As far as I could see, the snow mark shader that mimics a snowball impact already applies to Betty, BubbleG, and Pumper. BubbleG also already fires white snowballs.

- [x] Snow mark shader should be applied to Betty, BubbleG and Pumper
- [x] BubbleG weapon FX should be changed to white snowballs
- [x] Pumper weapon FX should be changed to white lightning bolts and trails
- [x] Betty weapon FX should be changed to white snowballs, lightning, drops (Betty causes no explosion in FT)
- [x] Boaster foam marks should be changed to ice puddles
- [x] Balloony explosions should leave snow white marks and delight color should be blue-white
- [x] Nipper projectile and mark shaders adjustments to reflect the snow ammo

 Also some weapon skin textures need to be changed:
- [x] Betty muzzle flash and skin shader adjustments to reflect the snow ammo
- [x] BubbleG muzzle flash and skin shader adjustments to reflect the snow ammo
- [x] Pumper muzzle flash shader adjustments to reflect the snow ammo
- [x] Nipper muzzle flash shader adjustments to reflect the snow ammo

**Comment by 3aTmE** [comment]
After Playing a few Freezetag rounds recently i can confirm that all Weapon effects are working like they should. 

Nothing obvious occurred during regular Gameplay.
