### ISSUE TITLE
CATCH: There is more than one Killerduck available or none

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#197]
It looks like the Killerduck holdable respawns at the original holdable spawn point while a player is holding it or while it is already spawned at another player spawn point. This results in more than one Killerduck holdable being available to be picked up. So more than one player can hold the Killerduck. Sometimes it is possible to shoot the one Killerduck, which then behaves as in other game modes.

Killerduck available while holding one:
![shot0016](https://user-images.githubusercontent.com/44040989/229364505-d0fa8165-9080-4bc9-ba83-eb4c13ec8f9d.png)

Two Killerduck items available (here randomly at the same spawn point)
![shot0018](https://user-images.githubusercontent.com/44040989/229364507-470ae04e-7bae-4658-b62b-4e06b9868341.png)

After picking both up, I was able to "shoot" one
![shot0022](https://user-images.githubusercontent.com/44040989/229364509-66c323f2-2538-4eb3-9675-1abfb60b82ef.png)

**Comment by mgerhardy** [comment]
should be fixed now. Thanks a lot

**Comment by kai-li-wop** [comment]
@mgerhardy: Most of the issue seems to be fixed, but there is still something that is not working properly that might be related. I was killed while holding the Killerduck, and randomly respawned at the same player spawn point where the Killerduck was spawned. So I randomly picked it up again right during respawn. I was not marked as a Killerduck carrier in the process, and the bots did not attack. When I went to drop the Killerduck using the use key, it didn't respawn, but fired it instead and then exploded. After that, there was no Killerduck in the game at all, so the game type was no longer playable. This might be hard to reproduce. I would like to do some suggestions how to handle the Killerduck dropping and respawning. I will add this in #167  tomorrow.

![Image](https://user-images.githubusercontent.com/44040989/229372852-879f03d5-900b-4688-9a54-6cbdf7733639.png)
