### ISSUE TITLE
Import SVN history

### ISSUE THREAD

**Issue by robo9k** [PadWorld-Entertainment/worldofpadman#2]
Besides the exports of the engine/game source code for releases, the code and assets lived in a SVN repository. @codemasher asked to have the full SVN history imported into GitHub, if possible.

Relevant links
* [GitHub Help on "Source code migration tools"](https://help.github.com/articles/source-code-migration-tools/)

**Comment by robo9k** [comment]
I found several checkouts scattered across backups, still have to figure out which is most recent, if any.
Repository points to `svn://svn.tjps.eu/WoP/trunk` so maybe @thiloschulz can help. Don't know if I'd have/could recover credentials, if it's still alive at all.

**Comment by thiloschulz** [comment]
here!

I still have complete SVN directory. What do you want me to do?

**Comment by codemasher** [comment]
Hey Thilo, long time no see! The easiest thing would be to give brain and perhaps me access to the repo, so that we could maybe import it - or you could do it by yourself if that's not too much of a hassle for you :)
btw. you have still a pending invite to this org!

**Comment by thiloschulz** [comment]
Actually, I still have the subversion server configured. I just tested it. It works.

**Comment by codemasher** [comment]
That's ok - i'm smiley, the website & forum person and brain is the one who wrote gamecode since v1.5.
I had an account on the bugtracker as *smiley* but i guess that's different from the svn?

**Comment by thiloschulz** [comment]
yep. do you have PGP? send me an email to thilo [ta] tjps.eu and I can give you login

**Comment by mgerhardy** [comment]
I have imported the whole commit history via git-svn and will publish the source code repository as an archived repo for historical reasons soon.

**Comment by codemasher** [comment]
thank you!

**Comment by kai-li-wop** [comment]
I think this can be closed now.

**Comment by codemasher** [comment]
I wonder what happened to the code from before 2009... if we had that, we could properly tag all releases there.
