### ISSUE TITLE
CATCH: Weapon switch animation and twisted killerduck position while holding

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#206]
While the killer duck is held in the hand, it is not possible to change the "weapon" using the mouse wheel, but it is still possible to change it using the keyboard weapon keys (1 to 0). The animation for changing weapons is played, although only the killer duck appears in the hand.

Also, the position of the killer duck depends on whether Punchy or another weapon was in the hand before. If it was Punchy, the killer duck will not be held correctly because the position of the weapon tag is different from all other weapons. I suggest always switching to Nipper before holding the killer duck.

**Comment by kai-li-wop** [comment]
@mgerhardy: It is still possible to play the weapon change animation by switching between Punchy and any other weapon. Press 1 and 2 to recreate this, if your keyboard layout is the same as mine.

**Comment by mgerhardy** [comment]
The previous commit wasn't meant to fix the initial issue - but it was somehow related. The weapon switch menu was just disabled - the second mentioned commit should now also fix the initially reported issue about switching-animations (tested in 3rd person view) without switching the weapon.

**Comment by kai-li-wop** [comment]
Looks god to me. I was not able to recreate the issue. Maybe @3aTmE can approve it?

**Comment by 3aTmE** [comment]
Same here! Everything seems completely fine on my end. :)
