### ISSUE TITLE
UI : Capture The Lolly (CtL) shows up as Freezetag (FT) in the Game Info Window

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#209]
### The Issue:
When starting a CTL Game with the Game Info Window enabled it would report the Game Type as FreezeTag (FT) instead of CTL.

![shot0001](https://github.com/PadWorld-Entertainment/worldofpadman/assets/84514074/4c5c0b2e-c707-4463-a570-9e0b0731b1b9)

### How to Replikate: 
- Make sure first that the Game Info Window is enabled 
- Create a CTL Game locally 
- Upon spawing you should be able to see in the Game Info Window that the wrong Game Type is displayed.

I'm using a executable build from the most recent WoP source Code.

**Comment by kai-li-wop** [comment]
Something is twisted:
- CTL --> FT
- FFA --> CTL
- FT --> FFAT

**Comment by kai-li-wop** [comment]
Should be fixed

**Comment by 3aTmE** [comment]
Just tested with the changes made. I can confirm the fix, nice!
