### ISSUE TITLE
ITEMS : Speedy warps the field of view way too much, makes the item completely unusable. 

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#212]
# The Issue : 

When running after picking the Item up the field of view gets badly distorted, making the item unusable in the progress. 
![shot0002](https://github.com/PadWorld-Entertainment/worldofpadman/assets/84514074/2770f8ec-64a1-4e4b-ad67-100457b4a218)

# How to reproduce ?
- Start a local game on any game mode and map which contains the speedy item.
- pick the speedy up
- start running

This issue seems new and only occurred after i build new binaries from the most recent code ( date of writing 01.10.2023 )

**Comment by kai-li-wop** [comment]
@3aTmE: I cannot reproduce this with the up to date code base. Please test if it still appears. Otherwise use the binaries from our side. Might be something wrong on your side?

**Comment by 3aTmE** [comment]
@kai-li-wop It might be! I just tried to replicate and was unable to. 
Closing this Issue. 
Something went probably wrong on my side.
