### ISSUE TITLE
CATCH : Score Issue

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#213]
# The Issue :
I just wanted to record some Gameplay to showcase the new Catch the Killer Duck game mode on YouTube. 

While recording one of the bots managed to score a whopping 202 points, despite the game being set to 50 :)

I uploaded the footage on YouTube : https://youtu.be/cU55h9mMaNU

# How to reproduce? 
- To be honest, i don't know.
- Happened quite random.

**Comment by kai-li-wop** [comment]
@3aTmE: Please try to reproduce this. thx.

**Comment by 3aTmE** [comment]
I played 3 rounds CTKD in total today. I was not able to reproduce this. I am still not sure what even caused this behaviour in the first place.

**Comment by kai-li-wop** [comment]
OK, I will close this for now as "fixed".
