### ISSUE TITLE
Score board show medal count of all players it seems, not only own medal count

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#218]
I just found out, that the score board shows the medal count of all players it seems, not only the own medal count. I implemented something wrong with 32b0cfd1a191d76c19c47e4114c320bcbe99739a I guess. I started 3 clients on the same computer and one scored PadHero. The score board of all clients showed 1 PadHero count. Should be indicated only for one client, the one who scored PadHero, not for all. Can someone please try to reproduce this?

**Comment by mgerhardy** [comment]
yes - cg.scores is an array - and you only took the first client. so every player will see the first players medals

**Comment by kai-li-wop** [comment]
PK, thx. Seems to be fixed on my side.

**Comment by 3aTmE** [comment]
Okay, i just tested it on my end with the most recent code base at the time of writing this comment. 

This issue seems to persists for me.
Weirdly , after a certain time the Value seems to "reset" and my own medals will be shown instead. But still, sometimes, the medals of some random client will show up instead of my own again. 



![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/84514074/06a0acba-dd9d-42e8-a5cc-465f6b12b6ef)


As you can see in the screenshot provided above, i got the medal for multiple frags, while having actually 0 frags of my own.

**Comment by kai-li-wop** [comment]
@3aTmE: Don't know. I had some longer test session in SYC Team, where most different medals can be won and all looks totally god. The scoreboard always shows my medal count correct. No sudden and unexpected number changes. I took the most recent code base and recompiled after 'cmake clean rebuild'.

**Comment by kai-li-wop** [comment]
@3aTmE: Probably you are right. Just received strange results in BB. Somehow wrong medal color red player with blue PadStar and blue player with red PadStar. Also the red received the PadStar medal while blue captured. What the heck? Wrong team allocation?

![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/0e350013-94d7-4a11-95b3-14930d94edb3)
![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/b4d6e78e-1401-47f4-a227-190c76b05cbc)

**Comment by kai-li-wop** [comment]
Now I could absolutely reproduce what @3aTmE experienced. Best to test in Big Balloon or SYC Team. For some time i had the wrong medal count and also the wrong team medal (red PadStar but being member of blue team). But after a while this settled and correct medals and values are shown. Totally strange.

**Comment by kai-li-wop** [comment]
Should be fixed with c6f0b03543cf2ad17bfe97075c0708411664855d and according to my tests, it is fixed. @3aTmE, can you confirm?

**Comment by 3aTmE** [comment]
> @kai-li-wop  Should be fixed with https://github.com/PadWorld-Entertainment/worldofpadman/commit/c6f0b03543cf2ad17bfe97075c0708411664855d and according to my tests, it is fixed. @3aTmE, can you confirm?

Just tested it in FFA, BB and SyC Team. Everything worked just fine! 👍
