### ISSUE TITLE
How to start the game

### ISSUE THREAD

**Issue by WilliamWangPeng** [PadWorld-Entertainment/worldofpadman#22]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/114642573-beb79900-9d06-11eb-9255-8eba325a7fe7.png)

thank you  
best regards to you  
William

**Comment by kai-li-wop** [comment]
Hi, you are missing the pk3 files, which is the necessary content of all game assets which you need to play the game. I recommend you to download first the latest version of WoP from the website. Also, we are back in early development of a new version, so I recommend you to stick to the latest stable release available, which is WoP 1.6 (https://worldofpadman.net/en/download/). Of course you could then apply your compiled binaries on the last stable version.
