### ISSUE TITLE
There is always they/them in the status messages when model selected

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#222]
From @3eatme: When i am using the "none" option all chat prints of the bots are also using they / them pronouns. After changing to any other Sex option the they / them pronouns of the Bot chat stays. No matter what other options I use.

Even after changing my player model the they / them pronouns of the Bot chat persists.

Okay, after i changed the Map the bots are still using they / them pronouns.

For me as a player they worked so far flawlessly.

_Originally posted by @3aTmE in https://github.com/PadWorld-Entertainment/worldofpadman/issues/199#issuecomment-1813290564_

**Comment by kai-li-wop** [comment]
For me it appears a little different: The issue occurs when switching back from any selected gender to the model's gender in player settings menu. The shown chat prints they/them from the none gender instead of the selected model's gender until I manually select another model. Same when the map changes, the model's gender is always gender_none until I selects a new model manually even though model is selected in the drop down.

**Comment by kai-li-wop** [comment]
Those are two issues. The event status related messages is a client side issue which should be fixed with 7f52dca1a5ec090fbdd36622470176912950a96f

The bot related issue probably needs a fix somewhere else. But it would be good to test if it still appears with the fix above. I would guess, yes.

**Comment by mgerhardy** [comment]
The problem is that the `ci->modelGender` variable is only known to the cgame - the game always uses the `ci->gender` value that the cgame transmitted - in case of selecting model, you get the value `GENDER_MAX` - which in turn translates to using they/them in all server generated messages.

**Comment by mgerhardy** [comment]
we will just always set the gender to the model gender if you switch the model (`ci->genderModel` should no longer be needed then)
