### ISSUE TITLE
Incorrect model size in player settings menu

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#229]
With introduction of the widescreen menu appeared an incorrect model size in the player settings menu. The model size is determined by the screen width. Since we have more space in the menu screen and we want to use it for the model, we need to determine the model size by screen height I guess.

**Comment by kai-li-wop** [comment]
Should be fixed with f32cf99ec43b67a63465f0a6e188592eacb97c1a

**Comment by 3aTmE** [comment]
Just tested it, i can Confirm the fix! 👍
