### ISSUE TITLE
BSPC: CTL code is missing

### ISSUE THREAD

**Issue by mgerhardy** [PadWorld-Entertainment/worldofpadman#23]

**Comment by robo9k** [comment]
Is this the same as robo9k/WoPPack#3 ?

**Comment by kai-li-wop** [comment]
This is connected I think. There have been adjustments for SYC and CTL game modes. But cyr needs to clarify.

**Comment by seldomU** [comment]
I don't have the sources anymore. If you really want to build mac/linux binaries, you'll have to reimplement it. From what I remember, there are no adjustments for the CTL gamemode and only one small change for Spray your color: the spray teleporters are ignored during the waypoint graph generation. With a bit of detective work, this should be doable.

There is a second change that is not critical and harder to replicate. Some maps come with a file of handmade waypoint connections that bspc then adds to the auto-generated ones. IIRC we didn't use this feature a lot, but there were a few cool jumppad acrobatics. We may not be able to reproduce this one.

**Comment by robo9k** [comment]
If the code is/was licensed under GPL, and I don't see why it wouldn't, then we have to provide source for the binaries we distribute.

**Comment by mgerhardy** [comment]
I've diffed the bspc version code that we have in the svn against https://github.com/TTimo/bspc 

The only real difference is in aas_file.c 
```diff
diff --git a/aas_file.c b/aas_file.c
index 9111cc8..7e1c059 100644
--- a/aas_file.c
+++ b/aas_file.c
@@ -470,6 +470,8 @@ void AAS_ShowTotals(void)
        AAS_ShowNumReachabilities(TRAVEL_STRAFEJUMP, "strafe jump");
        AAS_ShowNumReachabilities(TRAVEL_JUMPPAD, "jump pad");
        AAS_ShowNumReachabilities(TRAVEL_FUNCBOB, "func bob");
+       AAS_ShowNumReachabilities(TRAVEL_JUMPER, "jumper");             // cyr
+
 } //end of the function AAS_ShowTotals
 //===========================================================================
 // aas data is useless after writing to file because it is byte swapped
```

This doesn't look like the changes you meant

**Comment by mgerhardy** [comment]
Does maybe anyone still has the windows pdb files? That would make reversing quite easy.

**Comment by mgerhardy** [comment]
[bspcwop.zip](https://github.com/PadWorld-Entertainment/worldofpadman/files/6329196/bspcwop.zip)

Attached the source code archive from svn

**Comment by mgerhardy** [comment]
[0001-BSPC-diffed-against-latest-release.patch.txt](https://github.com/PadWorld-Entertainment/worldofpadman/files/6329202/0001-BSPC-diffed-against-latest-release.patch.txt)

This is the diff against the latest bspc version - maybe someone can judge whether the code in question is part of it.

**Comment by mgerhardy** [comment]
https://github.com/PadWorld-Entertainment/bspc

Looks like everything is there - linking is just not yet working, as libexpat is still missing. Will fix that soon

**Comment by mgerhardy** [comment]
https://github.com/PadWorld-Entertainment/bspc/issues/1
Continue the remaining work in that ticket - we basically have a version now - a pipeline that builds it and so on. Closing this one now.

**Comment by seldomU** [comment]
The diff looks good, there is stuff than I remember. Cool!
