### ISSUE TITLE
Ingame bg images need to consider narrow screens

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#230]
Since the introduction of the wide screen support bg images like scoreboard etc. are not drawn stretched any more. This leaves to gaps for narrow screen aspect ratios like 5:4. Therefore we need those images with longer "arms" ... MonsterPad holding the scoreboard and PADMAN holding the ingame menu board.

- [x] Ingame menu
- [x] Scoreboard

**Comment by 3aTmE** [comment]
Just tested it whit the recent codebase and can confirm the fix.
None of the in-game menus was cut off! 

I tested the following : 
- Set the game to a 5:4 aspect ratio (1280x1024 in my case)
- Start a local game
- Opened the Scoreboard, in-game menu board and the jukebox. 
- Repeated the steps again with the following aspect ratios : 3:2, 4:3, 1.80:1, 16:10
