### ISSUE TITLE
WoP bots don't know how to play One Lolly CTL

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#231]
The WoP bots don't know how to play One Lolly CTL. They pickup the neutral lolly and score by coincidence. The bot ai currently don't know about this new game type. I guess a lot can be adapted from the Team Arena code but WoP's bot code is quite different, so help is appreciated.

**Comment by 3aTmE** [comment]
Just played a round on wop_trashmapCTL with 6 Bots on the MosquitoBite difficulty.  

The Bots were able to play this mode just fine. :)
