### ISSUE TITLE
Linux homepath is ~/.local/share/.worldofpadman

### ISSUE THREAD

**Issue by zturtleman** [PadWorld-Entertainment/worldofpadman#234]
Current Linux homepath `/home/$USER/.local/share/.worldofpadman`

This is somewhat confusing to guess with it being a hidden "dot" directory while in .local/share/. It seems like it should be `/home/$USER/.local/share/worldofpadman`.

**Comment by mgerhardy** [comment]
I totally agree

```
#define HOMEPATH_NAME_UNIX ".worldofpadman"
```

I think we've discussed this before with @kai-li-wop - but I'm not sure about the outcome anymore. I would just remove the dot here to match the user expectation

**Comment by kai-li-wop** [comment]
I cannot comment the user experience on Linux but I would say, go for it.
