### ISSUE TITLE
Running wop.x86_64 +devmap <map> without sv_pure 0 results in no game window

### ISSUE THREAD

**Issue by zturtleman** [PadWorld-Entertainment/worldofpadman#236]
```
PadPlayer^7 Unpure client detected. Invalid .PK3 files referenced!
----- Server Shutdown (Server disconnected) -----
```

Without pk3 files and using default sv_pure 1, the server errors and client drops to menu except there is no game window. The audio plays and log shows renderer and ui were restarted. RE_Shutdown( 0 ) means the window shouldn't be destroyed.

ioquake3 with wop data + q3 qvms + sarge player and sv_pure 1, errors out but the game window isn't lost.

I'm at loss of what's wrong. Probably need to set break points in SDL to figure out why the window is destroyed or hidden.

Only tested on GNOME/Wayland with SDL (default) x11 backend.

[log.txt](https://github.com/PadWorld-Entertainment/worldofpadman/files/13538624/log.txt)

**Comment by kai-li-wop** [comment]
I can confirm this issue on Windows. Happens from time to time.

**Comment by kai-li-wop** [comment]
@zturtleman: can it be that 68f8977f43fd788b72ff15de5fdf502077ed6745 coincidently also fixed this issue. i don't have those random crashes right now.

**Comment by zturtleman** [comment]
No, it still happens for me every time. I'll probably look into it. Though I reported the issue in case I never actually get around to fixing it.

**Comment by kai-li-wop** [comment]
@zturtleman: It might be related, but every time WoP crashes, the antialiasing option is turned off again, even if I cancel the video reset after restarting WoP.

**Comment by zturtleman** [comment]
The window is closed when [SDL_Quit() is called by SV_Shutdown()](https://github.com/PadWorld-Entertainment/worldofpadman/blob/fd37c46e4c0d0273c553620c5ed780c2559b88b5/code/server/sv_init.c#L775). It was added for the server-side Discord support in https://github.com/PadWorld-Entertainment/worldofpadman/commit/781404fdd470dde6248069b0bff23d6ad5ad7e51.

**Comment by kai-li-wop** [comment]
@mgerhardy: Can you do anything about it to fix the issue. Would be good to find a solution. thx

**Comment by mgerhardy** [comment]
Thanks a lot - most likely an oversight from the unittests (before the null package worked properly in combination with the tests)

There was also another `SDL_Init()` call that doesn't hurt, but I've removed it, too.

**Comment by kai-li-wop** [comment]
Looks good to me. I could not reproduce this issue after the fix.
