### ISSUE TITLE
Unable to Execute server_settings.cfg

### ISSUE THREAD

**Issue by eliasstepanik** [PadWorld-Entertainment/worldofpadman#237]
**Title:** Unable to Execute `server_settings.cfg` 

**Description:**
I am experiencing an issue with starting a World of Padman server using the `wop-1.6.2-full-unified.zip` version. The server seems to be running, but I am unable to connect to it. Additionally, it appears that the server is having trouble executing the `server_settings.cfg` file.

**Terminal Log:**
wopdocker-wop-1 | ...
wopdocker-wop-1 | couldn't exec /wop/server/server/wop/server_settings.cfg

**Steps to Reproduce:**
1. Start the server using `wop-1.6.2-full-unified.zip`.
2. Attempt to connect to the server.
3. Observe the error message regarding the execution of `server_settings.cfg`.

**Expected Behavior:**
The server should start successfully, and I should be able to connect without any issues.

**Additional Information:**
- Server version: `wop-1.6.2-full-unified.zip`
- The Server runs using Docker (I checked if thats whats causing the issue but that doesn´t seem to be the case)

**Note:**
I have checked the existence of the `server_settings.cfg` file, and it seems to be present in the specified directory.
I also have a repo with my progress my files 'https://github.com/eliasstepanik/WOPDocker'

**Comment by mgerhardy** [comment]
should be `/wop/server/data/wop/server_settings.cfg` according to your dockerfile.

**Comment by eliasstepanik** [comment]
I am adding all configs from the  config directory. To the wop dir.

Then I start it using 
./data/wopded-linux.x86_64 +set dedicated 1 +set net_port 27960 +set com_hunkMegs 256 +exec /wop/server/data/wop/server-settings.cfg

But it still can´t find it. 

I also tried using a relative Path but no luck
./data/wopded-linux.x86_64 +set dedicated 1 +set net_port 27960 +set com_hunkMegs 256 +exec /data/wop/server-settings.cfg

**Comment by mgerhardy** [comment]
wop is using a virtual filesystem - make sure that server-settings.cfg in any of the search paths - and just do `-exec server_settings.cfg` (as far as I can see it should be fine to leave the file where it currently is - just remove the path)

**Comment by eliasstepanik** [comment]
Thanks that worked :)

**Comment by eliasstepanik** [comment]
Ok it worked sadly I can´t join the Server :(
I tested if the port is open on 27960/udp but I am not able to connect.

wop 1.6.2_GIT_523c835-2021-11-20 final linux-x86_64
SSE instruction set enabled

We are looking in the current search path:
/root/.padman/wop
./data/wop
./data/wop/wop_008.pk3 (4 files)
./data/wop/wop_007.pk3 (18 files)
./data/wop/wop_006.pk3 (582 files)
./data/wop/wop_005.pk3 (3224 files)
./data/wop/wop_004.pk3 (798 files)
./data/wop/wop_003.pk3 (296 files)
./data/wop/wop_002.pk3 (1903 files)
./data/wop/wop_001.pk3 (534 files)
7359 files in pk3 files
execing default.cfg
execing wopconfig_server.cfg
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
--- Common Initialization Complete ---
IP: 127.0.0.1
IP: 192.168.160.2
Opening IP socket: 0.0.0.0:27960
execing server-settings.cfg
execing rotation.cfg


For me the console above looks like it should be running but I can´t seem to get it to work
I am trying to join via sailehd.systems witch is pointed to the ip of the server. (Manully writing the ip does also not work)

**Comment by eliasstepanik** [comment]
Here is my server-settings.cfg file


//
//    World of Padman - example server settings
//
//    NOTE: Any line that starts with // is ignored by WoP.
//          Whitespace between commands is also ignored.
//

//
// Administrator info
//
// Do not forget to edit and uncomment the two lines below
sets admin "saile2204"
sets email "mail ..."

//
// Server name and message
//
// Name of the server. Can include color tags
set sv_hostName "Saile2204´s World of Padman Server"
// "Message of the Day". Can include color tags
set g_MOTD      "sailehd.de"

//
// Server settings
//
// Maximum number of players, including bots
set sv_maxClients "12"
// Enable Voice over IP
set sv_VoIP       "1"
// Maximum bandwith per player. VoIP needs additional bandwidth.
// You only need to set this if your server is on a home connection with
// small upstream bandwith, e.g. dial-up.
// A value of 9000 is for 12 sv_maxClients and sv_VoIP 1 while on a 1 Mbps upstream.
set sv_maxRate    "9000"

//
// Bot settings
//
// Enable bots
set bot_enable     "1"
// Automatically add 4 bots and kick them when humans connect
set bot_minPlayers "4"
// Bot skill, from 1 to 5. 2 is default
set g_spSkill      "3"

//
// Passwords
//
// Remote administration password. If not set, no remote administration is possible
set rconPassword ""
// Password needed for anyone to join the server. If not set, anyone can join
set g_password   ""

//
// Game settings
//
// Allow players to call votes for next map, kicking a player etc.
set g_allowVote "1"
// Do warmup at the start of every map
set g_doWarmup  "1"
// Duration of the warmup, 30 seconds
set g_warmup    "30"

//
// Map and gametype rotation
//
// Execute contents of "rotation.cfg"
exec "rotation.cfg"

//
// You can now load a map via "vstr nextmap"
//

**Comment by mgerhardy** [comment]
start docker with the host network - this is more a docker issue/question than a wop issue.
