### ISSUE TITLE
Sun lensflare not in center

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#239]
Looks like the sun and sun lens flare is not in center any more. See screenshot, should be at position of crosshair. Probably due to changes made with wscreen.

![shot0000](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/3067c8d7-39a4-40a2-838a-8316079fc4a8)

**Comment by kai-li-wop** [comment]
Code is in cg_lensflare.c. Seems not be an easy fix by simply applying "CG_SetScreenPlacement(PLACE_CENTER, PLACE_CENTER)" because it only centers the 640:480 ref screen and you then can see the edges in narrow and wide screen, where the lensflare effect is cut. Looks ugly.

**Comment by mgerhardy** [comment]
CG_AdvancedDrawPicA or the refdef2D still has a problem to cut off parts of the lensflares in wide screen mode

![lensflares](https://github.com/PadWorld-Entertainment/worldofpadman/assets/577713/efaa7f01-81a3-47ee-acc5-9f24d288fba8)

**Comment by kai-li-wop** [comment]
I closed it probably by accident.

**Comment by kai-li-wop** [comment]
upper screenshot is with CG_SetScreenPlacement(PLACE_CENTER, PLACE_CENTER)!
The following one is without it.

![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/68a4ff28-00c2-45bb-ac45-7a834e580ec3)

**Comment by kai-li-wop** [comment]
@mgerhardy: I have briefly tested many different formats. The good news is that nothing is cut off any more. The bad news is that the effect becomes more oval the wider the image becomes. In the 5:4 format it is then higher than it is wide. The effect is only really round in 4:3 format. This should actually be decoupled. The effect should always be round, regardless of the image format. It is currently being stretched.

### 16:9
![shot0000](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/23150c91-8de8-4765-aa5b-ed5facbc1f30)

### 5:4
![shot0001](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/1cd720a0-2510-41c1-92f2-4bad174ec4f3)

### 4:3
![shot0002](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/ffb7cb00-46d2-4401-a37f-f0eb77d6e4f9)

**Comment by kai-li-wop** [comment]
#240 has solved the issue for me. The lens flare now displays correctly in any screen resolution and aspect ratio. Great work and thanks to all contributors. The codebase looked pretty messy before ;)

**Comment by 3aTmE** [comment]
Just tested it with resolutions both in 4:3 and 16:9 aspect ratios and confirm this fix as working flawlessly! 👍
