### ISSUE TITLE
Unify HUD and scoreboard model and icon appearance

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#242]
The scoreboard and HUD sometimes show an icon or a model, like for the cartridge in SYC and the lolly in CTL/1LCTL. The killer duck in CTKD is only shown as an icon on the scoreboard and as a normal holdable on the right side of the HUD, but without the number, because we only have one duck and not five in CTKD. On the other hand, the selected weapon and ammo are represented by a simple 2D icon at the bottom left of the HUD. We also have two cvars: cg_drawIcons and cg_draw3dIcons, which have been reduced in functionality over the years. cg_drawIcons was meant to hide most of the icons from the HUD and scoreboard in Q3A, while in WoP it was completely cut from the HUD and only works with the scoreboard. cg_draw3dIcons was meant to replace all 3D models in the Q3A HUD with 2D icons, even the player's head. Again, most of this was disabled in WoP and simply doesn't work for all models, like the cartridge in SYC. This is an attempt to unify the look of those models/icons in the HUD and scoreboard, and to get the cvars working again.

- [x] center and scale all models/icons correctly with the line height in the scoreboard list and avoid overlapping
- [x] remove the cg_drawIcons cvar, because we always draw all icons in the scoreboard and HUD
- [x] restore the cg_draw3dIcons cvar, put it in the Options/HUD menu and make it work with all models in the scoreboard and HUD
- [x] replace all models in the scoreboard and HUD with the corresponding icons when cg_draw3dIcons is disabled, except the player's head, because the 2D icon has a background and it just doesn't look good
- [x] replace the killer duck icon with the model in the scoreboard and HUD when cg_draw3dIcons is enabled
- [x] hide the killer duck holdable icon when carrying the duck in CTKD on the right side of the HUD and replace it with the model/icon on the lower left side of the HUD to replace the weapon/ammo icon; there is no weapon working when carrying the duck, so don't show ammo/weapon info there and show the duck instead
- [x] replace the ammo/weapon icon with the ammo bottle model in the HUD when cg_draw3dIcons is enabled, except for Punchy and Spray Pistol; Punchy has no ammo bottle and Spray Pistol's ammo is already represented by the cartridges at the bottom right of the HUD; just draw the 2d icons for both of them, even when cg_draw3dIcons is enabled
- [x] Indicate in scoreboard if a player carries at least one cartridge in SYC FFA and SYC TEAM by showing a cartridge model/icon
- [x] unify the rotation speed for all models in the scoreboard and HUD

**Comment by 3aTmE** [comment]
Just , finally, tested this feature.

## What was tested?
**3D-Icons in the HUD and Scoreboard:**
- Rotation / Visibility of Ammunition. -> Works with no Issue
- Rotation / Visibility of the Killerduck in CTD -> Works in the HUD as well on the Scoreboard with no Issue
- Rotation / Visibility of the Lollies in CTL /  OLC -> Works in the HUD as well on the Scoreboard with no Issue
- Rotation / Visibility of Cartriges in SyC / SyCt -> Works in the HUD as well on the Scoreboard with no Issue
- Punchy and the SprayPistol using 2D images instead -> Works as intended! 

**2D-Icons in the HUD and Scoreboard:**
- Visibility of the Ammunition. -> Works with no Issue
- Visibility of the Killerduck in CTD -> Works in the HUD as well on the Scoreboard with no Issue
- Visibility of the Lollies in CTL /  OLC -> Works in the HUD as well on the Scoreboard with no Issue
- Visibility of Cartriges in SyC / SyCt -> Works in the HUD as well on the Scoreboard with no Issue

Or in short : i can confirm this as working :)
