### ISSUE TITLE
Accuracy counter shows 200% with one Imperius shot hits an enemy

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#247]
The accuracy counter always shows 200% when an Imperius shot hits an enemy, it should be 100% I think. Probably it's counting double.

7946b96c3cbbb8521cf0504ad7e586e30be9e5ef and https://github.com/PadWorld-Entertainment/worldofpadman/pull/245

**Comment by kai-li-wop** [comment]
Looks good to me. I tested with Imperius and could not reach more than 100% accuracy.

**Comment by 3aTmE** [comment]
> Looks good to me. I tested with Imperius and could not reach more than 100% accuracy.

Just tried it locally and was easily able to get 200 % Accuracy with a direct hit with from the Imperius. 

![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/84514074/d3b2fbd7-b4f6-421f-a0cf-f25280b62737)

Tested on the recent codebase from 21.01.2023

**Comment by kai-li-wop** [comment]
@3aTmE: Are you really sure you used the correct binaries and qvm's? I tested again with a clean rebuild and there is no way to achieve 200% accuracy with iMPERiUS. I tested with 15 bots in god mode shooting 50+ times with iMPERiUS hitting all the time at least one bot and the accuracy counter did not show more than 100%.

**Comment by mgerhardy** [comment]
was it really a direct hit? asking because that's hard to do with bots - so most likely no bot, but two human players? and also asking because you usually get your accuracy counter added up on a hit - and on splash

**Comment by kai-li-wop** [comment]
@mgerhardy: I tested again locally with 3 clients. I could achieve a direct hit with imperius two time but accuracy stays at 100%.

**Comment by 3aTmE** [comment]
> @3aTmE: Are you really sure you used the correct binaries and qvm's? I tested again with a clean rebuild and there is no way to achieve 200% accuracy with iMPERiUS. I tested with 15 bots in god mode shooting 50+ times with iMPERiUS hitting all the time at least one bot and the accuracy counter did not show more than 100%.

After testing with pre-built binaries from build #979, I also was not able to recreate it. 

I hope that puts both of your minds at ease! 😁

The issue was most likely on my end.
