### ISSUE TITLE
[ENHANCEMENT] Random color option for spray logo 

### ISSUE THREAD

**Issue by VesuviusVenox** [PadWorld-Entertainment/worldofpadman#248]
title

**Comment by kai-li-wop** [comment]
Hi, a little more info would be helpful. You want just an option to make the game select from the given spray colors randomly once or to change the color with every spray?

**Comment by VesuviusVenox** [comment]
Basically whenever you spray your color or shoot your insta gun, it chooses a random color instead of a set one. Hectic has a script that makes this possible, but it would be great to integrate this into the base game.

**Comment by kai-li-wop** [comment]
Should be implemented with #250
