### ISSUE TITLE
No lollies in Q3 maps with g_q3items enabled

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#249]
Seems that Q3 items support in WoP doesn't work with the lollies in CTL and 1LCTL. The Items don't spawn but there is also no warning, so the maps have those items. I approved it by playing in ioquake3. I used this map to test in CTL:

https://de.ws.q3df.org/map/speedyctf/

Set g_q3items to 1.

I could not find out what's wrong so far. The lollies simply don't appear.
I also tested in WoP 1.6.2, same thing.

**Comment by kai-li-wop** [comment]
Looks good to me. Tested CTL and 1LCTL with ColorStage: gametype and notgametype still work as expected. Also tested CTL with linked Q3 map, the lollies appear now. Excellent!

**Comment by syghfy** [comment]
![Image](https://github.com/user-attachments/assets/5cede156-00e5-42c8-aa69-2f32af8743a0)
All good here
