### ISSUE TITLE
UI: Bot names appear strange on arrow down event

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#251]
I must have mixed up something when implementing the bot names in the list (see 574a84a419d437d86539cefd6c81ee6836d891f8), but I cannot see what.

1. You need to have more than 12 player spots enabled in start server menu, let's enter 16.
2. Now go to select bots menu and the selected bots list on the right side now show the arrows.
3. Click the arrow down and up for a few times, you will see, that the bot names in the bot grid change to undefined values or disappear.

The arrows should control only the selected bots list on the right side and not the bot grid on the left side. So from where did I take the names shown there?

![shot0000](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/4beac032-7eb6-41e9-a391-b6a5ee6a12eb)

**Comment by kai-li-wop** [comment]
@mgerhardy: The issue still appears. When clicking down or up arrows on the right side with more then 12 bots in the list, the shown bot names on the left bot grid change and are shown strange. This should not occur. The up and down arrows should not influence the bot grid on the left. Only the left and right arrows should change the bot grid.

**Comment by kai-li-wop** [comment]
OK, now it seems to be fixed

**Comment by syghfy** [comment]
![Image](https://github.com/user-attachments/assets/9e8cc4ca-4ab5-43ba-95cb-bc10d4c8212e)
seems all good
