### ISSUE TITLE
UI: Menu option overlaps background texture

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#252]
In this screenshot, the output and input devices overlap with the background texture. ENTE asks for a possibility to shorten this dynamic content to a certain number of letters. Since the content is dynamic, we should have the option of specifying a maximum number of letters for the menu item shown and 3 dots should be added after trimming.

Example from screenshot: "OpenAL Soft on Lautsprecher......"

The content of the drop-down menu itself should not be trimmed when it is activated and displayed.

![grafik](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/c1becc65-bcd9-4f3f-b050-9c00748539d8)

**Comment by mgerhardy** [comment]
should be implemented now.

**Comment by kai-li-wop** [comment]
@mgerhardy: Would it be possible also to reduce the length of the white highlight box to the shorted string length?

![grafik](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/a0645136-4cfc-40d0-8f63-2938f479250d)

**Comment by kai-li-wop** [comment]
Looks good and seems to be fixed.

**Comment by 3aTmE** [comment]
Checked it on my end and i can confirm the changes made as working. 

The White boxes are appearing as they should and long text passages are shortened correctly.

![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/84514074/c297692a-fbd0-4d0f-91d6-01c1bd387ec9)
