### ISSUE TITLE
CATCH: Show the duck as a weapon in 1st person view

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#253]
ENTE asks if it is possible to show the collected KillerDuck like a weapon on the lower right side of the screen in Catch The KillerDuck game type. This would help to see that you collected it. The 3d model on the lower left part of the HUD is not enough it seems.

**Comment by mgerhardy** [comment]
I need more details - which model (exact path) and so on. Maybe a mockup of what was meant here.

**Comment by kai-li-wop** [comment]
I believe holding the killer duck in your hands was implemented once during the first test cycles of the CATCH game type, but was removed due to the hold icon on the lower right side of the screen that is displayed when the killer duck is held. We thought it was a kind of double display when the killer duck is held in the hands and the hold icon is also displayed on the right side of the screen. Also, the duck took up a large part of the right side of the screen in 1st person view.

The hold icon has been removed and replaced by the icon/model at the bottom left of the HUD, where the ammunition is now displayed. This means that there is now space on the right-hand side of the screen to hold the KillerDuck model in the 1st person view and ENTE wants to see it.

Model path: “models/weapons2/killerducks/pad_killerduck_pu”

It is interesting to note that this holdable is stored in the weapons folder, as it was first implemented as a weapon before it became a holdable.

**Comment by mgerhardy** [comment]
![wop-ctkd](https://github.com/PadWorld-Entertainment/worldofpadman/assets/577713/4f00d742-f703-4524-bd1c-8082b61ea14a)

in order to tweak the size or position, please use the cvars `cg_gun_x`, `cg_gun_y` and `cg_gun_z` after starting ctkd in dev mode

`\g_gametype 5; devmap wop_padgarden`

**Comment by mgerhardy** [comment]
the changes also might have influence on SyC game mode - so this should get re-tested, too (the weapon switch stuff in the spray room and when leaving the spray room)

**Comment by kai-li-wop** [comment]
Tested the Killerduck position and view and looks good to me. ENTE needs to give some feedback then. This could influence then the position of the duck in 1st and 3rd person view, but we will see.

I also tested SYC FFA & TEAM game types and both seem without issues. For me the weapon spray room in/out switch works like normal. I did not test the ping command issues. Maybe @3aTmE can confirm my test and also check for the ping command issues again. ;)

**Comment by 3aTmE** [comment]
Just played 2 rounds CTKD. 
The Killerduck displayed in 1st and 3rd person view just fine! :) 

I can't test the ping shenanigans since i am using only Linux on my machines where the ping command just works fine. 
This is something i would definitely  ask someone  to test in the Beta. 

It could break the Gametype on certain maps if this issue persists under windows.
