### ISSUE TITLE
CATCH: The first squeak of the Killerduck is a fail sound

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#254]
The first squeak of the Killerduck when collected is a fail sound, not the squeak sound in Catch The KillerDuck. Looks like it needs to be cached before used 1st time.

**Comment by 3aTmE** [comment]
Tried to replicate the issue on my end with recent changes made and was unable to. 

Seems to to be fixed! 👍
