### ISSUE TITLE
UI - Splasher Zoom Overlay is not displaying properly on every resolution

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#257]
## The Issue :

The Zoom Overlay of the Splasher is not displaying properly on every resolution. 
The so far affected resolutions are 1280x720 , 1600x900 , 1440x900. 
![SPLASAHER UI](https://github.com/PadWorld-Entertainment/worldofpadman/assets/84514074/ecccfc2d-e328-4c5f-bec5-4fc6cf22fcaf)

Tested with 1.7 DEV with the recent Codebase.

_This also affects the Injector._

## How to recreate this Issue :

- Start a local game
- Pick up the Splasher
- Set your display resolution to one of the affected settings (most visible on 1280x720)
- Zoom with the Splasher

**Comment by kai-li-wop** [comment]
Should be fixed with abeff03606b69060219e8eb8f5cfc51170a114ae

**Comment by 3aTmE** [comment]
Just checked it with the changes you made and can confirm this issue as fixed! :+1:
