### ISSUE TITLE
Placing boomie too close to lolly base while playing Big Balloon on Kai's Trashmap

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#258]
Reported by Ben the PadKing via Discord: While placing a boomie in the sewers near the Balloony spawn point the game reports "Too close to lolly base", but there is no lolly and no lolly base.

I could recreate the issue by standing there and trying to place a boomie. I looked into the map and I could not see any lolly spawn point or such. So this is a really strange bug.

![shot0650](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/5226d8db-972b-45fe-b989-db572c5939d2)

**Comment by kai-li-wop** [comment]
Seems that the code finds a red lolly at given coordinates, but there is none set in the whole map. Is this some out of boundaries issue?



![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/4b7551a4-63c7-4bb5-96e0-a4e8f211b91f)

**Comment by mgerhardy** [comment]
looks like you are using %i or %d for your console output - but the positions are floats and you have to use %f

**Comment by kai-li-wop** [comment]
This should be correct now. It's the coordinates of the bubbleg ammo bottle, but how can that be identified as a lolly spawn point? there are now strange flags set with this entity. I will make a test compile with it deleted to see if the error still appears.
![grafik](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/56afe71a-f55a-41ce-a4e6-7f294b78e413)

**Comment by kai-li-wop** [comment]
61589e67578414f9d07f5e80d8bc1fae839ff2c6 should implement a workaround to avoid this issue. The true reason is still unknown to me.

**Comment by 3aTmE** [comment]
I was not able to recreate this Issue with the recent codebase and can confirm it therefore as fixed.
