### ISSUE TITLE
Bots: bots keep camping on opponents team lolly position

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#26]
Ever since 1.5, bots have often struggled to play Capture the Lolly correctly. They get the correct lolly, then walk to their own teams base and walk right past where they should capture it - then they just go back to the other teams base to the exact spot where they collected grabbed it, and then camp there until they get killed. Although when i test it on my local server, this didn't seem to happen and they could capture it, although they still constantly walk off the map (colorstage) at a specific place. I may need to spend some time figuring out what causes them to do this, as on my network servers, they usually do.
~Ben the PadKing

**Comment by kai-li-wop** [comment]
With the implementation of bot support for 1LCTL (https://github.com/PadWorld-Entertainment/worldofpadman/pull/261) some changes and fixes were made, which could probably also solve the issue with camping at lolly spawn points. We need some long term dedicated server test if this issue still appears. 

To quote @mgerhardy: "There were definitely id problems in the bot files. There was an off-by-one with the flags. If it (this issue) was about the bot forgetting that it was the carrier, then 99% of the time it was due to the inventory."

**Comment by 3aTmE** [comment]
I played a CTL and a 1LCTL match to try to replicate the Issue. 

This was tested from the most recent available code from October the 29th. 

**What was tested?**

- Create a local CTL game with 5 Bots ( 3 Blue, 2 Red )
- Let the Bots of my team grab the Lolly.
- Check if the Bot bring back the Lolly and are able to score. ( They did! ✅ ) 
- Create a local 1CTL game with the same set-up. 
- Let the bots of my team grab the Lolly 
- Check if the Bot brings the Lolly to the enemy base and are able to score ( They did! ✅  ) 

Of course this testing only affects local games. 
I am curious how the bots will behave long term on dedicated servers. :)

**Comment by kai-li-wop** [comment]
I could not observe this issue on the beta server, so will close this ticket.
