### ISSUE TITLE
Music: music player restarts always on map change

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#26]
This has only been a problem since the 1.6 patch - but it is the same for everyone. Every time you join a map, or are on a server and go to nextmap, the music always starts with dieselkopf1 (padrock album) and the first track "down the hatch". You can skip to any song later in the music menu during the round, but no matter what you save or select, it will start at this same song very round. Or the same story if you have custom music in the game, such as by Neurological. In my case on my local server the first track on that album does this.
~Ben_the_Padking

**Comment by robo9k** [comment]
I've only skimmed the logs while loading maps locally with the new engine binaries and it seems to be working fine, unless I'm misunderstanding?

Setup in console:
```
]\logfile 2
]\developer 1
]\fs_debug 1
```

Some relevant parts from log with me pressing <kbd>N</kbd> for next song, then loading a new map via console:
```
[WoP Music]: Playing "^3padrun^7"
S_StartBackgroundTrack( wopmusic/dieselkopf1/02_padrun.ogg, <nextsongCMD> )
FS_FOpenFileRead: wopmusic/dieselkopf1/02_padrun.ogg (found in 'Z:\World of PADMAN\wop\wop_004.pk3')
^3WARNING: music file wopmusic/dieselkopf1/02_padrun.ogg is not 22k stereo
[WoP Music]: Playing "^3padtrail^7"
S_StartBackgroundTrack( wopmusic/dieselkopf1/03_padtrail.ogg, <nextsongCMD> )
FS_FOpenFileRead: wopmusic/dieselkopf1/03_padtrail.ogg (found in 'Z:\World of PADMAN\wop\wop_004.pk3')
^3WARNING: music file wopmusic/dieselkopf1/03_padtrail.ogg is not 22k stereo
..
FS_FOpenFileWrite: C:\Users\brain\AppData\Roaming\Padman\wop\playlist.dat
..
FS_FOpenFileRead: playlist.dat (found in 'C:\Users\brain\AppData\Roaming\Padman\wop')
..
S_StartBackgroundTrack( ,  )
..
[WoP Music]: Playing "^3padtrail^7"
S_StartBackgroundTrack( wopmusic/dieselkopf1/03_padtrail.ogg, <nextsongCMD> )
FS_FOpenFileRead: wopmusic/dieselkopf1/03_padtrail.ogg (found in 'Z:\World of PADMAN\wop\wop_004.pk3')
^3WARNING: music file wopmusic/dieselkopf1/03_padtrail.ogg is not 22k stereo
..
handle 2: wopmusic/dieselkopf1/03_padtrail.ogg
..
FS_FOpenFileWrite: C:\Users\brain\AppData\Roaming\Padman\wop\playlist.dat

**Comment by robo9k** [comment]
To debug this, the following might be relevant:
* Cvar `wop_AutoswitchSongByNextMap`
* How are songs switched, pressing bound keys, using the menu, automatically?
* How are maps switched, is it a local listen or remote dedicated server?
* Contents of `playlist.dat` before and after

**Comment by kai-li-wop** [comment]
I think that "warmup" may also play a role. I can remember that there was an issue, with music an warmup and that you changed something in the code to prevent problems. See SVN 2127, 2131 and 2132.

**Comment by kai-li-wop** [comment]
I took some time to check the behavior in the latest dev version in local game.

- The song is switched on map change automagically, when option auto switch song is enabled in the sound menu. So this is expected behavior.
- The song restarts on map change automagically, when option auto switch song is disabled in the sound menu. So this is expected behavior.
- Also pressing N for next song is working fine. 
- But the console keeps spamming: "WARNING: unhandled AL error: Invalid name" when the player changes to the next song automatically without map change or pressing N.

**Comment by mgerhardy** [comment]
I can not reproduce this here - maybe some actions are needed before it starts to flood? Are there any details to get the flooding?

**Comment by mgerhardy** [comment]
Closing this one - opened another one for the console flooding: https://github.com/PadWorld-Entertainment/worldofpadman/issues/94
