### ISSUE TITLE
InstaPad respawn protection

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#260]
Roland stated via Email: "I mainly play Last Pad Standing with InstaGib in WoP 1.6.2, and often when I get shot, I get killed again immediately, right after respawning, with no chance to dodge, shoot, jump or whatever.... Protection for a short time after respawning would help here. Is there such a thing in WoP 1.6.2?"

All we have right now is some kind of spawn protection by starting with higher health points. This feature is useless since InstaPad features the instant hit weapon Injector which always "kills" instantly. So a solution might be to protect a spawning player by making him invincible for a few seconds after spawning.

**Comment by kai-li-wop** [comment]
6 seconds spawn protection in InstaPad game mode should be implemented with 91557d43612541fd0348084f736053a8b82f10b4

ToDo: Add some visuals that spawn protection is active

**Comment by kai-li-wop** [comment]
With bca196d9cd1f9c3159c7cedf9ab110514174bac8 a visual effect was added to the HUD. The health and shield bars should flash as long as spawn protection in InstaPad mode is active. This effect is only shown after a re-spawn, not when entering a match.

**Comment by 3aTmE** [comment]
I just tested it and can confirm this as working. 
(UI and the Spawnprotection itself)

The only thing that i might add is an indication when other players are spawn protected. Like a glow (or maybe a Shader like Padower ) or something. 

As for now i can't tell if a player has Spawn protection or not.

**Comment by mgerhardy** [comment]
The effect on other players was discussed but not implemented as it might a) increase there visibility and b) would favor spawn campers if they would see the protection, too. (One also can't find this in instagib implementation of Xonotic afaik.)

**Comment by kai-li-wop** [comment]
@3aTmE: The InstaGib+ mod for Quake 3 Arena gives the player the battlesuit as a visual effect, but WoP has no such thing. Giving the PadPower would also force all other effects, like playing the PadPower sound with every shot. Then I would have to reduce the PadPower powerup to just that visual effect in the InstaPad and disable everything else. It would be possible, but as @mgerhardy said, I think it would bring more disadvantages than advantages. If you lose a shot against a spawn protected player, that's your bad luck. ;)
