### ISSUE TITLE
WOP Crashing on launch with SEGV Fedora 38 & 39

### ISSUE THREAD

**Issue by WebDragon** [PadWorld-Entertainment/worldofpadman#268]
an strace can be found here with the original bug report which has been hearing crickets since I first reported it; just updated it for F39 when the prior went EOL. I share with you in the hopes of it getting noticed and fixed. 

https://bugzilla.redhat.com/show_bug.cgi?id=2238642

**Comment by mgerhardy** [comment]
which version of world of padman? why is the binary quake3 and not worldofpadman?

**Comment by WebDragon** [comment]
@mgerhardy It's the installation for Fedora Linux 39 

Apparently it has to download the quake3 binary because they can't include it with the RPM ?  not sure about the licensing issues 

```
09:59 PM {1000} scott-desktop: ~>$ rpm -ql worldofpadman
/usr/bin/worldofpadman
/usr/share/appdata/worldofpadman.appdata.xml
/usr/share/applications/worldofpadman.desktop
/usr/share/icons/hicolor/32x32/apps/wop.png
/usr/share/icons/hicolor/scalable/apps/wop.svg
/usr/share/quake3/worldofpadman.autodlrc
09:59 PM {1001} scott-desktop: ~>$ rpm -q worldofpadman
worldofpadman-1.36-44.svn2102.fc39.x86_64
```
from the rpm's info: 

> World of Padman uses the GPL licensed ioquake3 engine, however the Wop data-
files are not freely redistributable. This package will install a World of
Padman menu entry, which will automatically download the necessary datafiles
(1GB!) the first time you start World of Padman.

**Comment by mgerhardy** [comment]
I doubt we can help here, wop is not using the `ioquake3` binary (it's based on the ioq3 sources) - it uses its own binary called `wop.x86_64` - overall this looks a lot like a packaging issue that should get fixed by fedora. We don't have any stake in the fedora package though.

**Comment by WebDragon** [comment]
@mgerhardy  Would you mind terribly much following up on the fedora bug report with your comments to that effect ? so the bug receives at least _some_ action?
