### ISSUE TITLE
BadPaddy's icons for blue and red are not representing the model colors

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#271]
As you can see on the screenshots, the icons of the red and blue BadPaddy skins don't represent the correct colors of the hair and headband. This was mentioned by [HEART] on Discord.

![shot0000](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/cfd3e361-8d4d-4258-b8f3-4d3c46a69e0a)
![shot0001](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/2cda5807-ec90-4fd0-b74c-3831208997bf)

**Comment by kai-li-wop** [comment]
Should be fixed with 6784807d051e83f2d1aff453d9b52488adac8d74.

**Comment by 3aTmE** [comment]
Just tested this locally and can confirm this as fixed.
