### ISSUE TITLE
Maps: camping hideout in CybJourney CTL

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#28]
When jumping sideways into the toilet paper on wop_journeyCTL, you can get inside of said toilet paper.  ~3aTmE!
![shot0104](https://user-images.githubusercontent.com/44040989/114822065-cdaf5180-9dc1-11eb-92b5-3d9f2c9e8971.jpg)
![shot0105](https://user-images.githubusercontent.com/44040989/114822068-cee07e80-9dc1-11eb-81cf-c6850150cc0a.jpg)

**Comment by kai-li-wop** [comment]
Should be fixed with 3bf1d822eeb36b3525d14fabe6773a35cd7aa217.

**Comment by 3aTmE** [comment]
Just tested it on both bases, i can confirm the fix ! 👍
