### ISSUE TITLE
The "Create" server menu never keeps the selected bot skill and always resets it to Flower Power

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#280]
The "Create" server menu never keeps the selected bot skill and always resets it to Flower Power. We could sync it with the g_spSkill cvar originally used for Quake 3 Arerna's single-player mode. See https://github.com/ioquake/ioq3/pull/600 as a reference.

**Comment by kai-li-wop** [comment]
fa9d4b7c05de61b44df9a1c4f3f65d991d510a27 provides a solution for this.

**Comment by 3aTmE** [comment]
It is fixed as long the game is running but going to reset when i close the game and reopen it again. 

This was tried using the most recent code from October the 29th. 

**What was tested?**
- Adding Bots in the Create Menu 
- Changing the Difficulty to "Brutal blue noses" 
- Leaving the "Select Bots" Menu
- Entering the "Select Bots" Menu
- Check if the chosen skill still applied ( it did ) ✅ 
- Leaving the Create Menu completely
-  Re- Entering the Create Menu
- Entering the "Select Bots" Menu and check if the chosen skill still was applied. ( it did! ) ✅ 
- Closing the Game
- Starting the Game again
- Entering the Create Menu
-  Entering the "Select Bots" Menu and check if the chosen skill still was applied. ( it did not ) ❌

**Comment by kai-li-wop** [comment]
fa9d4b7c05de61b44df9a1c4f3f65d991d510a27 synchronize the create server bot selection and ingame add bots menus with the g_spSkill cvar originally used for Quake 3 Arerna's single player mode. The ingame add bots menu already used this cvar, but never saved it.
So the intention was to have the main menu and the ingame menu correspond and communicate the same value and keep it the same as long as WoP is running. It was not intended to save the value of the g_spSkill cvar as a user preference for a restart of WoP. I think it would also not be necessary.
Marked as done for now.
