### ISSUE TITLE
Dieselkopf albums should always been first in the list

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#282]
ENTE wants the Dieselkopf covers always be first in the music menu. Currently I don't know how it is sorted but `mightypete` album comes before `dieselkopf1` album. We need a way to set the order of the current available album folders in WoP. All other custom music folders, if added by users later on, should come after this and the order then doesn't matter.

Apart from that, when music is playing the currently played album is shown when the menu is called. This behaviour should stay untouched. So the issue it is about the order, not what album is shown first, when the menu is called.

Something like this already exists for the player models order and the bots list order in the respective menus. So probably this could be used as a reference.

**Comment by kai-li-wop** [comment]
This looks good so far. Thanks for the quick implementation. I figured out that dieselkopf3 is first and then comes dieselkopf2 followed by dieselkopf1. As far as I remember the sort order also depends if the files/folders a packed in pk3 files or not. dieselkopf1 should be first but I guess it will be as soon as the files are packed in pk3s. We will see, I will close this ticked for now.

**Comment by 3aTmE** [comment]
I can confirm this Issue as Fixed and working as Intended. 
Tested on the recent codebase from 08.11.2024.

**What was Tested** 
- Checking if the right album is shown on opening of the music menu. 
- Checking if the albums are flipped in the right order ( dieselkopf 3 -> dieselkopf 2 -> dieselkopf 1)
- Checking when after setting up an own queue for the music, the right album will be shown from the currently playing song (eg. down the hatch from dieselkopf1 displays dieselkopf1 when beeing played)
