### ISSUE TITLE
Add info message to the player if he wants to collect  the killer duck directly after he dropped it in CATCH

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#283]
A player cannot pick up the killer duck for 5 seconds if he dropped it, so an info message would be useful here to inform him when he tries to pick it up again within this time span. 

"You can't pick up the KillerDuck for a while!"

For example, there is also a message in syc ffa when you try to collect your own cartridge, which is not possible.
"You can't grab your own cartridge!"

**Comment by kai-li-wop** [comment]
@mgerhardy: The message appears when you drop the killer duck, but not when you try to pick it up. Is this intentional? The message should only appear when the player tries to pick it up, not every time he drops it.

**Comment by kai-li-wop** [comment]
Works for me now like expected. thx

**Comment by syghfy** [comment]
![Image](https://github.com/user-attachments/assets/8630a238-1d06-4c5b-96b3-82faf381a8de)
all good
