### ISSUE TITLE
CATCH: Bots change to a diffrenet weapon after picking up the KillderDuck in Catch

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#285]
I don't know how but the bots are able to change to a weapon directly after picking up the KillerDuck in CATCH. Simply start a game with several bots and the bots immediately switch to a weapon and hold a weapon model in hands while carrying the KillerDuck. Also by switching as spectator into the follow mode I cannot see the bot holding the KillerDuck in 1st person view. Seems only to work for bots, not for human players.

**Comment by mgerhardy** [comment]
![shot0001](https://github.com/user-attachments/assets/8dd1a8d4-44f7-4dd3-b7be-d383e7a8e957)
![shot0000](https://github.com/user-attachments/assets/878b7f87-c19c-40f7-9f0c-511a90c16d30)

reproducible here

**Comment by mgerhardy** [comment]
> I've set `g_speed` to `1` 10 seconds after the bot has collected the killerduck

**Comment by kai-li-wop** [comment]
But should be the golden KillerDuck, not the Punchy hand puppet. Some bots also hold other weapons. Join the match and get the KillerDuck by yourself. You will hold the golden KillerDuck, but bots won't. They switch quiet fast to any other weapon they like and if collected.

**Comment by mgerhardy** [comment]
21b75e4806eda111447acb79319f42cd5cb25a21 introduced this

**Comment by kai-li-wop** [comment]
Good, it wasn't me. ;)

**Comment by kai-li-wop** [comment]
Looks fixed to me.
