### ISSUE TITLE
UI: There is an unnecessary arrow in the gametype help menu

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#286]
See picture:

![grafik](https://github.com/user-attachments/assets/e48a1641-a36d-4deb-a396-36e5db499c4e)

**Comment by kai-li-wop** [comment]
cfea65a introduced this.

**Comment by kai-li-wop** [comment]
Arrows are fixed, but buttons do not switch the pages any more. What have I done?

**Comment by 3aTmE** [comment]
I can confirm this as fixed. The Arrow on the Game-Menu is gone and the Arrows on the Help-Menu are switching the pages properly.
