### ISSUE TITLE
1LC: BamBam is missing a few textures and effects in One Lolly Capture

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#287]
The BamBam is missing the health bar and missile effects in One Lolly Capture, so shots are also not visible.

reported by ~Hectic & Blu123

![shot0000](https://github.com/user-attachments/assets/1234e66b-fac9-45fc-9dce-976b19e97293)

**Comment by 3aTmE** [comment]
I can confirm this issue as fixed. Bambams Health-Bar appear now properly.
