### ISSUE TITLE
UI: In the Vote menu, Yes and No are written illegibly one above the other

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#288]
In the Vote menu, Yes and No are written illegibly one above the other

reported by ~Hectic & Blu123

**Comment by kai-li-wop** [comment]
Should be fixed with f6aceb23b3f1963a9c5cf07aa15b7b13ef05c756

**Comment by 3aTmE** [comment]
I can confirm this issue as fixed. The Text are no longer written illegibly one above the other any more.
