### ISSUE TITLE
UI: Net/VoiP menu hides some VoIP options when turned off, but does not disable them

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#289]
In Setup->System->Net/VoIP, some settings are only hidden and not deactivated. If you hover over it with the mouse, the tool tips are still displayed and you can probably still change the settings there.

reported by ~Hectic & Blu123

![shot0000](https://github.com/user-attachments/assets/b931e238-2073-42f5-a95e-9242a43ce462)

**Comment by syghfy** [comment]
![Image](https://github.com/user-attachments/assets/34085400-66c1-4015-ad6d-6694681c51a4)
hidden options are properly disabled
