### ISSUE TITLE
Code: Flickering entities - pushing the entities limit

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#29]
There seems to be a hardcoded limit of drawn entities at the same time. This effects usually big maps filled with a lot of items and other entities. But also when using BOASTER not all of the foam puddles are drawn when there are a lot of player online at the same time. So this already affects especially the current TrashMap. The effect on the items are best visible in this [video](https://youtu.be/Rs1LoLRamhg) by 3aTmE! When I remember correct @seldomU already tried to have a look at the issue back in 2011, but WoP v1.6 was too close to release date, there was not enough time to implement a solution.

**Comment by zturtleman** [comment]
Entities popping in and out of view may be MAX_SNAPSHOT_ENTITIES (256). It's not the game entity limit MAX_GENTITIES (1024) as walking around doesn't automatically remove/add items like in the video.

Wolfenstien: Enemy Territory and Spearmint use MAX_SNAPSHOT_ENTITIES 512. This is a network compatibility break. I don't think it requires any other changes than the define.

Though Quake 3 just doesn't handle large open maps well. Maybe it's possible to use areaportals(?) on the maps to help split the PVS (potentially visible set) to reduce entities sent to clients. (I don't know the mapping side well.)

q3map2 has global fog support for Wolf:ET that automatically splits the map into chunks with limited view range. It might be possible to add a q3map2 feature (if it does not exist) to only apply this to entities so far away entities aren't sent to clients. (Though again, I don't know this area well.)

**Comment by kai-li-wop** [comment]
With 6b997baf4c3114f3ebc130476f7718ee8cdc4f2b I raised MAX_SNAPSHOT_ENTITIES to 512. Would be good to get some feedback from @3aTmE if this helps to solve the issue.

**Comment by mgerhardy** [comment]
maybe we should bump the protocol version, too

**Comment by kai-li-wop** [comment]
It already is. Due to repacking all the pk3 files we already changed PROTOCOL_VERSION to 72. WoP 1.6 has 71 afair.

**Comment by 3aTmE** [comment]
Just tested it on my end locally with a test map containing 512 entities in total.

Unfortunately, it seems that only half of the entities will still be rendered.

**Comment by 3aTmE** [comment]
@kai-li-wop  Like requested here is the compiled test map I've used  : 


[ENT-TEST BSP.zip](https://github.com/PadWorld-Entertainment/worldofpadman/files/13627882/ENT-TEST.BSP.zip)

**Comment by kai-li-wop** [comment]
Console spams: "CL_GetSnapshot: truncated 510 entities to 256". This leads me to MAX_ENTITIES_IN_SNAPSHOT and not MAX_SNAPSHOT_ENTITIES. I raised MAX_ENTITIES_IN_SNAPSHOT to 512. Looks like all entities are drawn now. No errors as far as I can see.

@zturtleman: Spearmint uses "MAX_SNAPSHOT_ENTITIES 512" and "MAX_ENTITIES_IN_SNAPSHOT 256 * MAX_SPLITVIEW while MAX_SPLITVIEW is set to 4. I guess it would be safe then to set MAX_ENTITIES_IN_SNAPSHOT at least to 512, same like MAX_SNAPSHOT_ENTITIES. What do you think?

![shot0000](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/4472b14f-da04-4c9d-a72a-92a55f7e8d83)

**Comment by kai-li-wop** [comment]
a17e767e5afba5df9c435c0dfa8c82aeba508567 raises MAX_ENTITIES_IN_SNAPSHOT to 512.

**Comment by zturtleman** [comment]
Yeah, that makes sense.

**Comment by 3aTmE** [comment]
Just tested it with my ent_test.bsp map and can confirm that all 512 entities of this map are displayed properly! 👍
