### ISSUE TITLE
Default `con_scale` to 2 for better usability

### ISSUE THREAD

**Issue by Calinou** [PadWorld-Entertainment/worldofpadman#296]
On 1.7.0-beta1, with the default `con_scale 1`, console text looks tiny on a 4K display:

![image](https://github.com/user-attachments/assets/f2254a09-8178-4bd8-9042-e5ea4c5cf2ee)

It's a lot more readable with `con_scale 2`:

![image](https://github.com/user-attachments/assets/dce23adc-2e38-4ee7-8b78-b05b768cc1d5)

On 1920x1080, `con_scale 2` is still usable, with console text roughly matching the menu options' text size:

![image](https://github.com/user-attachments/assets/5ec03f0c-05a7-4b6e-bea2-bb0c4b51068a)

**Comment by mgerhardy** [comment]
Also see #118

**Comment by Calinou** [comment]
> Also see #118

The character spacing issue mentioned in https://github.com/PadWorld-Entertainment/worldofpadman/issues/118#issuecomment-2161267985 reminds me that the font would probably be easier to read if it had reduced character spacing (though not as much as shown in that example, which was the result of a bug). The letters are spaced quite a bit right now, which makes it harder to read.

This would apply not just to the console font, but to the general UI/chat font as well.
