### ISSUE TITLE
Powerup icons don't show on HUD if powerup time is greater than 999 seconds

### ISSUE THREAD

**Issue by Calinou** [PadWorld-Entertainment/worldofpadman#299]
On 1.7.0-beta1, if you have more than 999 seconds remaining of a powerup, it won't show up on the HUD anymore as seen on the videos in https://github.com/PadWorld-Entertainment/worldofpadman/issues/298.

This can't occur in a real game, but it can occur with cheats enabled if you use the `/give` command enough times with any powerup name after it.

I suggest displaying the powerup icon in this case but with no time visible, similar to how the ammo count is hidden in GTA games if you have more than 9,999 bullets remaining (to denote "infinite" ammo).

**Comment by kai-li-wop** [comment]
It's a bug but with a low priority I would guess. I keep it in the backlog
