### ISSUE TITLE
v1.7.0-beta1: In Harm's Huette, the splasher spawner has been swapped with the betty spawner.

### ISSUE THREAD

**Issue by ninjakitty844** [PadWorld-Entertainment/worldofpadman#304]
The betty spawner on the desk is now a splasher spawner. And the splasher spawner on the high shelves is now a betty spawner.

I think these two spawns have been accidentally swapped.

**Comment by kai-li-wop** [comment]
Hi, this was done on purpose to lower the advantage of the higher ground in combination with Splasher. The map is quite open and you can survive there forever, if you are good enough. So we won't "fix" this.
