### ISSUE TITLE
DISCORD: The server messages spam a little bit Discord and other stuff

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#305]
The Discord messages integration spams a little bit too much, so we could give the server admin some control over it.

we could add a new cvar to give more control about what should be posted. Currently it is
- human joined --> flag 1
- new map started --> flag 2
- score --> flag 4

So add `discord_webhook_content` with flags 1, 2, 4 to let the admin decide what to send. Also we should add the server name because probably other servers will send messages too.

I can see Unvanquished using a similar feature via irc but they bundle the information:

`4 people (0+10 A, 4 H, 0 S) playing kapitanbomba on Map&Bot Testing EU | no broken maps! | 0.55.0 https://play.unvanquished.net/82.165.236.249:27960`

So they combine players, map and server name which I like somehow. And they add a connect link. Maybe this would be much better, instead of an additional cvar. I think the score and map start are not important to send. Keep it to humans joining and combine the information like Unvanquished is doing it.

**Comment by mgerhardy** [comment]
![Bildschirmfoto vom 2024-11-01 20-46-29](https://github.com/user-attachments/assets/e7608183-e12a-46ab-87ad-6edf98ab47b6)

**Comment by kai-li-wop** [comment]
Looks very good so far. I would like to suggest to change the join message to a more general status message, always when a human player joins instead of sending the name.

`3 PadPlayers (2+2 B, 1+3 R, 0 S) playing wop_padgarden`

Explanation: 3 PadPlayers (2 humans + 2 bots Blue Noses team, 1 human + 3 bots Red Pads team , 0 spectators) playing the PadGarden map.

This should be the default message, so flag 1. All other should be optional and not default. This would also reduce spamming. I am thinking of 10 servers sending all those messages.

**Comment by kai-li-wop** [comment]
Instead of sending the map name we should send the long name from the arena file?!?

`ENTE's PadKitchen` vs. `wop_padkitchenBB`

**Comment by kai-li-wop** [comment]
I mark this as done for now.

**Comment by kai-li-wop** [comment]
Also, with the recent changes, it happens that there are a few messages sent almost at the same time. It seems that the join message is sent when bots join. I think we agreed to limit this to only human players joining. Also, we should implement some kind of timeout between messages when multiple humans join in close succession to avoid this kind of message flooding.

Would it be possible to add the game type to the message string, e.g. `5 PadPlayers playing CTL on ENTE's PadAsia`? The short name would be sufficient.

![Image](https://github.com/user-attachments/assets/eea70bd0-f892-470f-915b-34696c0681d0)
