### ISSUE TITLE
PadShop has missing textures on the MonsterPad pencils

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#306]
PadShop has missing textures on the MonsterPad pencils.

~reported by Adri{HUN} & Ben

![grafik](https://github.com/user-attachments/assets/83b113d3-3b8d-426f-8d0e-664053ef6a55)

**Comment by kai-li-wop** [comment]
This is due to the folder name change. The solution would be to write a shader if ENTE does not recompile anyway.

**Comment by syghfy** [comment]
![Image](https://github.com/user-attachments/assets/4749f1f0-b36e-4145-9c94-b7b0a494b186)
The head textures are indeed back
