### ISSUE TITLE
Fatal: AAS not initialized BotAISetupClient failed on wop_plane on all gametypes

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#308]
Fatal: AAS not initialized BotAISetupClient failed on wop_plane on all gametypes

~reported by Ben

**Comment by kai-li-wop** [comment]
I know, I was not able to provide the aas file in time. Due to massiv use of curved surfaces in the map the aas compiler fails, so I have to create a simple version of the map to create an aas file from this. I need to connect the simple map version aas with the final map version which is a pain in the a**.

**Comment by 3aTmE** [comment]
I can confirm this issue as fixed. Was able to add Bots to a TFFA match on wop_plane just fine.
