### ISSUE TITLE
Kicked out with error message when changing sunlight mode

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#309]
Kicked out with error message when changing sunlight mode

`CL_GetServerCommand: a reliable command was cycled out`

This happens every time you change the sunlight mode to dynamic / hybrid or off and press accept. It gets to the end of loading the map, then you get kicked out with this error. 

Note - this error message seems to appear every time you change more major settings while on the server. It didn’t kick me out when just playing locally.

~reported by Ben

**Comment by kai-li-wop** [comment]
Not sure about his. Need to try. But this would be connected to an ioquake3 feature. Maybe something for @zturtleman?

**Comment by mgerhardy** [comment]
I can not reproduce this. `r_sunlightMode` was changed from the ui while you are in a running game (from what to what?) as client connected on the 1.7 beta server? or a local match?

**Comment by kai-li-wop** [comment]
I think he means playing on the beta server. I also tried to reproduce this with given information but was not able to. So I will close this as not planned for now.
