### ISSUE TITLE
FREEZETAG: stuck with the floater sound and animation the whole time

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#310]
If using floater when you are frozen on freezetag, you are stuck with the floater sound and animation the whole time

~reported by Ben

![grafik](https://github.com/user-attachments/assets/b140f70f-4aa1-4574-bd22-27fe41b94b25)

**Comment by kai-li-wop** [comment]
Looks fixed on my side.

**Comment by syghfy** [comment]
Can't use floater while frozen anymore, no sound either so fixed on my end too
