### ISSUE TITLE
Imperius ammo can be collected even when you have the maximum quantity

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#311]
You can collect the ammo even when you have the maximum quantity. All other weapons don’t allow you to collect ammo once you have full ammo. This in fact has been the case ever since 1.5. It was back in 1.1 / 1.2 days where you got 3 imperius by default and could get up to 5 that the ammo worked correctly. When you had 5, you could stand on the ammo and not collect it. I would guess there is a limit setting for the ammo or something that needs setting to 3. 

~reported by Ben

**Comment by 3aTmE** [comment]
I can confirm this issue as fixed. I was not able to pick Imperius ammunition when holding the maximum quantity of rounds of 3.
