### ISSUE TITLE
UI: Smaller tooltips

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#312]
ENTE would like to see smaller tooltip popups. Since nearly every menu option has a tooltip they take a lot of space in the menu. Would it be possible to lower the font size for those tooltips by some percentage? We would need to try what percentage would be suitable.

**Comment by mgerhardy** [comment]
check out `q_shared.h`

`#define PROP_TINY_SIZE_SCALE 0.6`

**Comment by 3aTmE** [comment]
i can confirm this as working as intended. The tooltips are now smaller than before.
