### ISSUE TITLE
TrashMapCTL: BamBam can be placed in trees and you can shoot through them

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#313]
Looks like there is a weapon clip missing.

![shot0000](https://github.com/user-attachments/assets/25db1573-090c-4695-9613-126baf98ab23)
![shot0001](https://github.com/user-attachments/assets/2bc91399-2a9b-477c-a1bf-5735bca63009)

**Comment by syghfy** [comment]
![Image](https://github.com/user-attachments/assets/10dde7a3-7bad-400d-a7d8-65bcaadba0c0)
![Image](https://github.com/user-attachments/assets/156b101d-42b2-4646-820b-1f23f3a01c7f)
The tree is fully intact now :p
