### ISSUE TITLE
Floater goes crazy in Catch the Killerduck

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#315]
As you can see in the demo file, the floater in Catch the KillerDuck goes crazy when you pick it up while NOT holding the KillerDuck.

"But the real problem appears between minute 2:00 and 3:00. I was trying to pick up another floater: I went to pick up another floater, and I immediately threw it away - picked it up - threw it away - picked it up - threw it away... Only when another player grabbed the floater did it end.

~reported by Hectic

[20241101214111-168.119.185.219.27963-wop_padship.dm_72.zip](https://github.com/user-attachments/files/17610587/20241101214111-168.119.185.219.27963-wop_padship.dm_72.zip)

![shot0006](https://github.com/user-attachments/assets/e10b347a-eb32-41ab-9543-5666f3102fd2)

**Comment by mgerhardy** [comment]
`Pickup_Holdable` has this code part that I don't understand from game design side

```c
	if (g_gametype.integer == GT_CATCH && other->client->ps.stats[STAT_HOLDABLEVAR] > 0 && other->client->ps.stats[STAT_HOLDABLE_ITEM] != 0 &&
		other->client->ps.stats[STAT_HOLDABLE_ITEM] != MODELINDEX_KILLERDUCKS) {
		// already has a holdable, drop it in this game mode
		G_DropHoldable(other, 0.0f);
	}
```

why is a player who is not the killerduck dropping holdables (except the killerduck)?

5ba4aa61d402ab37a57b85b46ed545412bdc2bf4

this looks wrong and was only intended to be done for the killerduck player - but not for others.

**Comment by kai-li-wop** [comment]
Sure, only the KillerDuck holder should drop all holdables except the KillerDuck when picking it up. Not sure why you implemented it this way. Other players should get holdables like usual.

**Comment by kai-li-wop** [comment]
I could reproduce the bug in the current beta and can approve the fix in the current dev version.
Steps to reproduce:

1. start PadGarden Night in Catch game type
2. add one bot
3. go and collect the Floater from the bird house and wait there
4. let the bot collect the KillerDuck
5. collect the Floater again  when it respawns while you still have the first one

**Comment by 3aTmE** [comment]
I can also confirm this issue as fixed.
Tested on the recent dev code from 08.11.2024. 

**Steps Taken :**
- Start a local Catch the Killerduck game on wop_padship
- Add a single bot
- Grab the floater
- wait at the floater spawn until a second floater spawns while holding the first one. 
- Collect the second floater
- Check if the reported issue re-appears. -> It did not! ✅
