### ISSUE TITLE
BamBam health indicator won't show in Vertex

### ISSUE THREAD

**Issue by HazmaToxic** [PadWorld-Entertainment/worldofpadman#317]
Bambam's health indicator and fire effects won't show when Lighting turned into Vertex mode, instead missing textures appear.
But when turned back to Lightmap, the issiue was gone. Maybe this was supposed to happen? Not sure.

![wop17bugreport1](https://github.com/user-attachments/assets/1a8edc41-927b-4d57-a82f-e228320b2ed8)

I was messing with options and this happened.

**Comment by kai-li-wop** [comment]
@HazmaToxic: Please make sure if this only happens in "One Lolly Capture" or also in "Capture The Lolly" game type while switching between lightmap and vertex. A similar bug is already identified but only when you are in One Lolly Capture and has nothing to do with vertex oder lightmap options.

See #287

**Comment by HazmaToxic** [comment]
I will be checking out. And I am going to give more details about this.

**Comment by HazmaToxic** [comment]
> @HazmaToxic: Please make sure if this only happens in "One Lolly Capture" or also in "Capture The Lolly" game type while switching between lightmap and vertex. A similar bug is already identified but only when you are in One Lolly Capture and has nothing to do with vertex oder lightmap options.
> 
> See #287

I've looked again. The problem wasn't about Vertex. It is like you said, happens in only one lolly capture mode. Sorry for wrong report, didn't want to cause any misleading. @kai-li-wop 
This issue case can be removed. Thank you.
