### ISSUE TITLE
Maps: New path options in CybJourney

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#32]
For better gameplay and to avoid the massive killing and blocking in the single middle passage between the train parts, new path options must be added into the map CybJourney.

**Comment by kai-li-wop** [comment]
Should be added with 3bf1d822eeb36b3525d14fabe6773a35cd7aa217, see description there.

**Comment by 3aTmE** [comment]
Nice! Just tested it! 👍 

So far i was not able to find anything weird. 
So only thing i haven't tested yet is the 1CTL support. 

### What was tested? 
- Checked the console for shader and BSP validation warnings (there were none) 
- The Amount of Padshards on both bases.
- The suitcase on both bases, if it is clipped proper or not. 
- All changes to the weapon positions are made on both bases.
- All changes to the item positions are made on both bases.
- The clipping of map models
- The new paths working on both bases
- the via mover animated parts of the map ( no clipping, not being able to squash the player, etc)

So, yeah. All the changes of the map are implemented well!

Can't speak about the effects on the game play yet. That's something the beta test will tell us :)
