### ISSUE TITLE
Bots: crash - S_FindName: empty name

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#32]
Dunno why it crashed but here is a bug report. WoP gave me the option to just copy it to clipboard and paste. I was just hopping, my guess is one of the bots I was playing with did something to crash it ~Shadow
[message.txt](https://github.com/PadWorld-Entertainment/worldofpadman/files/6315425/message.txt)
[message(1).txt](https://github.com/PadWorld-Entertainment/worldofpadman/files/6315426/message.1.txt)

S_FindName: empty name - ya, that shouldn't happen. Without a stack trace or reproducible steps it's difficult to track. ~brain

**Comment by mgerhardy** [comment]
The error message doesn't even exist anymore. I suppose this should be closed, due to lack of information and a missing guide on how to reproduce it.

The ERR_DROP was converted into a warning on the console.
