### ISSUE TITLE
Setup/Player menu: Graphical errors with Fatpad and FATTY

### ISSUE THREAD

**Issue by cinnamon189** [PadWorld-Entertainment/worldofpadman#320]
In the Setup/Player menu, if Fatpad and FATTY gesture or switch weapons, there are a few spots on the upper body where the clothes disappear so you can see the skin instead.

**Comment by kai-li-wop** [comment]
Not sure what exactly is the issue. Can you provide a screenshot of the issue? maybe you can highlight the spots on the screenshot.

**Comment by cinnamon189** [comment]
![shot0000](https://github.com/user-attachments/assets/f353ab81-a483-4860-8611-a8aa63916a65)
My viewer does not seem to include any marker tools. So again, please observe the upper part of FatPad's body (same issue with FATPAD).

**Comment by kai-li-wop** [comment]
Ok, I understand the issue and it is known. We currently don't have the capacity of fixing FatPad and this model needs a complete rework anyway. So I will close this issue as not planned for now.
