### ISSUE TITLE
(Supposed) Typo in Credits: "spend" vs "spent"

### ISSUE THREAD

**Issue by cinnamon189** [PadWorld-Entertainment/worldofpadman#323]
In the final section of the credits it says that the team members "often spend little time with" their friends and family. That would be very sad, because it would mean that it has been like this for 20 years now. Maybe you mean "spent"?

**Comment by 3aTmE** [comment]
I can confirm this issue as fixed. 
Tested on recent dev code from 08.11.2024.

**Steps Taken**
- Start the game
- Go to the credits
- Check if the typo was still there -> It was not! ✅ 

A lil bit OT: I really forgot how slow the Credits scrolls :)
