### ISSUE TITLE
Bots do not notice you if you steal an item from them while having the Visionless

### ISSUE THREAD

**Issue by cinnamon189** [PadWorld-Entertainment/worldofpadman#329]
If you have the Visionless and pick up an Item right in front of an opposing (PadLilly) bot, it will still not notice your presence. One should think they do, much like they can see you for a while if you attack them while having the Visionless.

**Comment by kai-li-wop** [comment]
Holding the ViSiONLESS determines whether or not the bots can see you. They will attack you if you start shooting, but not if you pick something up in front of them. They cannot see you, so why should they attack? They just see that the item is gone, but they don't know where to shoot. Only when you shoot will they see where the shots came from. In my humble opinion, we don't need to change anything here.

**Comment by cinnamon189** [comment]
Well, I was not sure how consistent and human-like their behaviour should be. If bullets appear out of nothing, they can conclude that someone is there, so I was expecting that they can detect invisible Pads also if an Item suddenly vanishes. But, I think I could very well live with the current behaviour :)
