### ISSUE TITLE
Sound: FLOATER holdable emitts no sound when used

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#33]
A general bug that I'd forgotten to mention that has been hanging around since the upgrade to v1.2 or maybe it was OK in v1.5 too. However, FLOATER never continuously makes sound. It is inconsistent and most of the time just emits the purple smoke and no sound at all. In v1.2, it made sound every time you used it. ~Ben the PadKing

**Comment by kai-li-wop** [comment]
This issue came with v1.6. I faced it also but only when playing online. In local offline matches it works fine for me. I think this bug was already fixed years ago in the old SVN repo by brain, but did not make it into the v1.6 patch. It was planned to be shipped with v1.6.1 back then. We simply need to make sure, if it still occurs after the Martins engine update, which is based on the last SVN version, which also included the fix.

**Comment by mgerhardy** [comment]
The sound code is located in `CG_PlayerPowerups`. https://github.com/PadWorld-Entertainment/worldofpadman/blob/main/code/cgame/cg_players.c#L1834

This looks perfectly fine - we would need another online session to double check whether this still applies.

**Comment by kai-li-wop** [comment]
This bug still applies. When joining the beta 1.6.1 server and using the floater with 1.6.1 client, it still does not emit sound. But it works on a local match perfectly against bots.

**Comment by mgerhardy** [comment]
It also works fine for me when playing a LAN game and when running a dedicated server on my hetzner server and connecting with two clients.

**Comment by kai-li-wop** [comment]
All tests on @mgerhardy's server have worked fine so far. Hectic has also started to investigate the problem and it seems to be related to @robo9k's beryllium mod. We need to investigate here how this is caused by the mod, but it is not a problem on our side. I therefore consider the problem to be solved.
