### ISSUE TITLE
FridgeWars map: "shelfs" must be "shelves"

### ISSUE THREAD

**Issue by cinnamon189** [PadWorld-Entertainment/worldofpadman#331]
This concerns the "location strings" (?) for "blue upper shelfs", "blue lower shelfs", "red upper shelfs" and "red lower shelfs".

**Comment by kai-li-wop** [comment]
Or better "compartments", but is a little long to read fast.

**Comment by kai-li-wop** [comment]
"shelfs" replaced by "shelves"

**Comment by cinnamon189** [comment]
Well, DeepL does offer "shelf" as an option, even if it only comes in fourth place. So, "shelves" might be a bit less idiomatic than "compartments", but it still seems to be idiomatic enough :)

**Comment by 3aTmE** [comment]
Just started a game on fridgewars locally with bots and can confirm the string change from "shelfs" to "shelves" as working as intended.
