### ISSUE TITLE
LPS: Crosshair and Medals are shown in LPS spectator mode

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#332]
When all lives are lost in LPS, the player goes into spectator mode. This is not the usual spectator mode, but the waiting mode, where the player behaves like a spectator. In this mode, the player will still be able to see the crosshairs, crosshair names and medals on the scoreboard. After following other players, the crosshairs and medals will show the status of the last player followed.

To avoid this problem, we should remove the crosshair, crosshair names and medals from the "Wait" mode.

![shot0000](https://github.com/user-attachments/assets/94cec2aa-3704-4870-a6d0-093d8e6c8f72)
![shot0001](https://github.com/user-attachments/assets/b203102e-76e2-4298-b121-855e6a1f3d70)

**Comment by syghfy** [comment]
![Image](https://github.com/user-attachments/assets/cad2c877-e4c6-472e-b9de-7186dd488917)
medals and accuracy are hidden and it says "WAIT" now when out of lives
