### ISSUE TITLE
LPS: The scoreboard doesn't show the lives left with g_lps_flags enabled

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#334]
The scoreboard is missing the number of lives left in the score/lives column. Should not just show the current score.

![shot0006](https://github.com/user-attachments/assets/fcee9d3c-dcb4-4af2-9734-c47ae3cfaac4)

**Comment by kai-li-wop** [comment]
Should be restored now and look like this. Was introduced with a08b3bd0ea678a1d39aa5d4110d271e4de4051c7.

![shot0007](https://github.com/user-attachments/assets/9093d46a-e6a2-4c17-8ec0-c5364fc8fb3c)

**Comment by syghfy** [comment]
![Image](https://github.com/user-attachments/assets/91c97619-9fdc-4ff1-ada6-12d359aca52a)
Can confirm it looks how it's supposed to be

**Comment by kai-li-wop** [comment]
Impressive accuracy. ;)
