### ISSUE TITLE
UI: In-game help menu does not change the content texture

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#336]
The in-game help menu does not change the content texture when the arrow buttons are pressed.
WoP 1.7.0 beta 2 

~reported by Hectic

**Comment by kai-li-wop** [comment]
Introduced with c312c32102505119b8568e3c9cf47f27286b2d8d while trying to fix #286.

**Comment by 3aTmE** [comment]
I can confirm working the help menu as working as intented with the recent codebase.
