### ISSUE TITLE
Code: Get rid of file suffixes in the code

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#35]
There are still extensions like TGA and WAV in the hardcoded paths to textures and soudfiles, which cause files in OGG and PNG format not to be included automatically, for example player icons in the menu. Now I did not want to do this myself, because I do not know if this can also break something if you do it globally. I would have liked to implement this already now in v1.6.1, because then in the meantime e.g. player models can be released as addon for WoP from the community, which already contain PNGs and then remain also compatible for WoP v1.7, provided that we do not make further fundamental path adjustments with the player models.

**Comment by mgerhardy** [comment]
In general the extensions are stripped and not taken into account - if there are locations where they are used, please let me know the exact issue - otherwise we would most likely modify almost every source file and would diverge from ioq3 a lot.

**Comment by kai-li-wop** [comment]
I just tested by adding a png icon of a custom player model and it was shown in the players menu correctly. In WoP 1.6 it was already possible to use png in maps or such format, but not in the menu for player icons. This limitation seems to be gone with the engine update.

**Comment by kai-li-wop** [comment]
I think this can be closed as all related PRs got merged, If not, reopen.
