### ISSUE TITLE
Map: bad camping position in airplane

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#35]
Added from old bugtracker and affects WoP 1.6.

In map wop_airplane, there is a location on the lid of an open stowage compartment that is easy to reach, but easy to defend. This could be a big problem with LPS. ~Hectic

![shot0010](https://user-images.githubusercontent.com/44040989/115154972-f19ebb80-a07d-11eb-8d66-2eec92dafd02.jpg)
![shot0011](https://user-images.githubusercontent.com/44040989/115154974-f2375200-a07d-11eb-81a8-dae62c74b334.jpg)

**Comment by 3aTmE** [comment]
I tried to replicate this myself. 

Seems to be fixed in 1.7; I was not able to pull it off anymore.

**Comment by kai-li-wop** [comment]
@3aTmE. The thing is, that Oregano4 only put a bot clip up there but not a player clip. I simply changed the texture to player clip. This takes away some height of the ceiling but not one should be up there anyway.
