### ISSUE TITLE
Killerducks stack and get stuck

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#37]
Added from old bug tracker and affects WoP 1.6.

When throwing killerducks if you throw them all very fast while looking down a bit they will stack on each other and all get stuck in 1 place until they explode. When you look at the screenshot they look like there moving but they were 100% stuck XD. Also sometimes killerducks get stuck on each other when travelling when they bump into each other. ~Psychic Pad

![shot0012](https://user-images.githubusercontent.com/44040989/115156660-a4bee300-a085-11eb-98e6-00945ce44801.jpg)

**Comment by Calinou** [comment]
I wonder if an "unstuck" procedure can be added if the killerduck's average speed in the last second was below a certain threshold (which indicates the killerduck is likely stuck).

This unstuck procedure would likely try to teleport the killerduck around by a small amount on the X and Y axis, then the Z axis if no suitable position is found.

**Comment by mgerhardy** [comment]
The ducks are no longer colliding now - I've removed the corpse clip mask entry

(The idea about the unstuck operation would be worth a try, too)
