### ISSUE TITLE
UI: Console keeps spamming models/wop_players/padman/... not found"

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#45]
The console constantly spams in developer mode in a very high write rate "models/wop_players/padman/... not found" if an alternative skin for Padman was selected. This is a mystery to me, since the skin file is definitely there and from my point of view it is correct. Also the "WARNING: shader tag_weapon in skin" I do not understand. It must be part of the skin file. If I change the order of the entries in the skin file, it grumbles about one of the other lines. But the skin is correct so far and I can't find any differences to the other alternative skins of the other models. All this is also not a big problem, provided that one has not just activated the developer mode. Nevertheless, it is annoying when testing in developer mode, if you want to search the console for other, perhaps important messages. All those messages disappear too quickly then.

![consoleskin](https://user-images.githubusercontent.com/44040989/118539119-53bb1100-b74f-11eb-923d-71cd0c98379f.jpg)

**Comment by kai-li-wop** [comment]
This should be fixed now. To test this, type `developer 1` into the console and start a map. Select PadRock, StonePad, BioPad or PadSoldier as player model. No warning should appear in the console, as shown in the screenshot above.

**Comment by 3aTmE** [comment]
I can confirm the fix! 

Started an local game, selected BioPad as Playermodel and used the Command `developer 1` as requested. 

This is my Console output :


![Image](https://user-images.githubusercontent.com/84514074/221408915-a321c1bc-3bdc-4d47-b4e8-6b728ede0344.jpg)
