### ISSUE TITLE
UI: Music menu does not focus on the currently played album when called

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#48]
This is not directly a bug, but it affects the user experience. The music menu always loads the alphabetically first album when called, which certainly makes sense if no song has been selected for a playlist yet. However, once a playlist has been compiled, the music menu should always display the album from which a song is currently playing when called. Currently it just takes too long to click through all albums to get to the currently played song. By the way, the PadMod didn't have this animation where the album pans from right to left with the hand holding it.

Tasks to perform
- [x] Always show the album of the currently played song (if one is played) when calling the music menu
- [x] Speed up the initial start of the music menu
- [x] Speed up the process of switching albums

**Comment by kai-li-wop** [comment]
7bd2ec4dd8efbcb6ad9943ce3011ec5b8e2ad9e8 should speed up the process of initial start and switch albums.

**Comment by 3aTmE** [comment]
I can confirm the intended behavior.
The right album will show up when i open up the menu.

I Tested all albums by setting one Song from each album and checking after each song change if the right album is displayed.
