### ISSUE TITLE
UI: Featuring more chat options in WoP

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#51]
Unlike Quake 3 Arena, WoP already has a modified display of chat messages, which even scales with the user's resolution. So far, the user can select different display durations with and without a player icon, whereby the Long and Long (icon) options, for example, currently do not offer the same display duration. So there are currently 4 display durations offered:

- 3 and 8 seconds without icon
- 5 and 10 seconds with icon

The display time is influenced by con_notifytime, where a preceding negative sign currently activates the display of the player icon. 
Since not only chats but also all other events are shown in the display, the sole selection of the display time is no longer sufficient. On full servers with more than 10 players, the events overlap in such a way that the chats scroll out of the screen too quickly that they can hardly be seen and the set longer display time is barely reached. This is especially problematic in team games, and only a total of 4 lines are displayed.
The default disabled team chat display (basic feature of Quake3) could be used in this case, but is currently not optimized for the WoP HUD. There it would be possible to set the number of chat lines (up to 8 via cg_teamchatheight) and the display time (via cg_teamchattime). Actually I had the idea to include the teamchat officially and make it selectable, but there is just no space for it in the HUD. So it would be better to transfer a part of these functions to the current chat display. The following steps and additional options would make sense from my point of view to enhance the chat experience for the user:

- [x] Add a page for chat options to the game options menu (3 pages layout)
- [x] Separate notification display time and chat icon option into two menu options
- [x] Therefore it would be helpful to add a new cvar cg_drawChatIcon to simplify the necessary menu code
- [x] Notification time option should offer useful intervals like 2, 4, 6 and 8 seconds (short, default, long and maximum)
- [x] Option to enable only team chats (say_team) or at least to filter other chats in team game modes.
- [x] Expanding the amount of chat lines to use more space, maybe up to 8 (check with team overlay)
- [x] Could be helpful to have an option to enable the user to adjust the chat height 
- [x] Probably needs a new cvar cg_chatheight, similar to cg_teamchatheight
- [x] Option to disable the chat beep for people who find it annoying
- [x] Option to disable bots chatting for people who find it annoying

Screenshot of the current situation in WoP:
![shot0002](https://user-images.githubusercontent.com/44040989/123229008-33147280-d4d6-11eb-8bae-73aed670ef50.jpg)

Screenshot of the current situation in in Q3A (ioquake3):
![shot0001](https://user-images.githubusercontent.com/44040989/123229290-6eaf3c80-d4d6-11eb-99ab-13f7a78179c5.jpg)

**Comment by kai-li-wop** [comment]
To complete this extension, there are basically two items left open.

1. chatheight is implemented as a CVAR and therefore a menu option, but I don't know how to modify the existing code so that the variable is taken into account. So far I have only raised the maximum and chat messages from 4 to 8. But I don't know how to modify the code loop, so I need some support here.

2. teamschats only option is also implemented in the menu. However, the original behavior is such that when turned on, all non-team chats are generally hidden regardless of game mode, which is rather inconvenient. It would be good to change this feature so that when the "teamchats only" option is turned on, the chat is really only reduced to teamchats in team game modes and not in non-team game modes too. I need support for this implementation as well.

**Comment by kai-li-wop** [comment]
Currently there is still the following problem. You can start a match with e.g. chatheight set to "Maximum" (8 lines) and then everything works. But if you set the chatheight in the match itself to "Expanded" (6 lines) at runtime and then you type something in the chat in quick succession and the 6 lines are then displayed or reached, WoP hangs up and the display freezes.

For reproduction It is best to set Notification Time and Space both to maximum and then only reduce Notification Space. Then several times in quick succession always enter something in the chat and confirm, so that one reaches the currently set maximum line height.

**Comment by mgerhardy** [comment]
This script helped to reproduce the issue: [issue51.txt](https://github.com/PadWorld-Entertainment/worldofpadman/files/7935322/issue51.txt) - just copy to `~/.padman/wop/issue51.cfg` and do `exec issue51.cfg`


should be fixed in 6af1f3ce6895e023c645f51e122cd6bedc174f57

**Comment by kai-li-wop** [comment]
Tested and seems to be fixed. All new chat options are implemented.
