### ISSUE TITLE
Maps: Missing texture on wop_trashmap and wop_trashmapBB

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#52]
### Missing Texture on Trash Map and Trash Map Big Baloon

One side of the Wall got a missing Texture. 
Nothing really that someone would see when playing ingame because it being a rather hidden place.

you can reach this Area by walking over the roof gutter to the right side.

![shot0293](https://user-images.githubusercontent.com/84514074/128624445-cdd30781-eb02-4c0c-9fad-c68569f60b16.jpg)

![shot0294](https://user-images.githubusercontent.com/84514074/128624447-7af11574-67c2-44a4-97ca-5540ebe7d2e2.jpg)

**WoP Version:**
1.6.1 Beta
**OS**
Windows 10, 64 Bit

**Comment by kai-li-wop** [comment]
Should be fixed with e36ccbecefae7e926abc2ca07a303616f5bb4684

**Comment by 3aTmE** [comment]
![Image](https://user-images.githubusercontent.com/84514074/179352035-1ada6059-ff53-45de-97a7-b0603479183b.jpg)

Yes, i can confirm the fix! 👍
