### ISSUE TITLE
OPENGL2: Glowing , Pulsating bits of Environment when using Opengl2 on wop_trashmap 

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#54]
https://user-images.githubusercontent.com/84514074/140037049-4a98e133-538e-44f9-84f5-4ee327efc368.mov
(please ignore the flicker, it's not present when ingame and most likely due some wrong OBS settings on my end)

### The Issue

When using the OpenGL2 renderer while playing on wop_trashmap bits of the environment starts to glow and pulsate.
When playing with OpenGL1 everything renders just fine.

Im using right now World of Padman 1.6.1 RC but it is also present in the World of Padman 1.6.1 beta.

### How to replicate
On wop_trashmap simply Switch over to the OpenGL2 renderer via `/cl_renderer opengl2` and restart the renderer with `/vid_restart`

### My System

**OS:** Windows 10
**RAM:** 16 GB, DDR4
**CPU:** AMD Ryzen 5 3600
**GRAPHICS:** AMD Radeon x580
**WoP Version:** 1.6.1 RC

**Comment by mgerhardy** [comment]
Maybe related to https://github.com/ioquake/ioq3/issues/521

**Comment by zturtleman** [comment]
This can be worked around using `r_mergeLightmaps 0`. The only downside is maybe less performance but it probably doesn't really matter much. More details in https://github.com/ioquake/ioq3/issues/622.

**Comment by kai-li-wop** [comment]
@zturtleman: I tried r_mergeLightmaps 0 but without any effect. The workaround doesn't work on my side.

**Comment by zturtleman** [comment]
Oh, it also requires r_sunlightMode 0. Though that prevents using "r_forceSun 1" dynamic sun shadows.

I had more time to think about how to actually fix it. So see #243 that doesn't require any cvar changes.

**Comment by 3aTmE** [comment]
The Issue seems to be _mostly_ resolved! 
The affected geometry pulsates just a _little_ bit now!
Definitely a improvement!

https://github.com/PadWorld-Entertainment/worldofpadman/assets/84514074/2d17f0c7-a581-4645-9cc7-dc5301976660

**Comment by kai-li-wop** [comment]
@3aTmE: This is normal due to lightmap distribution on several textures. It also pulsates the same in OpenGL1.

**Comment by 3aTmE** [comment]
> @3aTmE: This is normal due to lightmap distribution on several textures. It also pulsates the same in OpenGL1.

Okay, good to know. Everything works as supposed to then :)
