### ISSUE TITLE
Map:  Players can clip into the Toiletpaper on wop_journeyctl

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#55]
I know, this one is already well known. Just adding it here for completion sake. :)
![Journey_toilet](https://user-images.githubusercontent.com/84514074/140513289-857e2b09-d4cc-465a-a00b-820c2b265bea.jpg)

### The Issue:

With a good placed weaponjump from the toiletseats in the restrooms players can jump inside of the Toiletpaper on wop_journeyctl.

![Journey_toilet2](https://user-images.githubusercontent.com/84514074/140513593-47d820d0-2537-4f35-89ef-f0396340bb88.jpg)

### How to replicate:

Jump from the lid of the toilet seat via a weapon jump from slightly below into the toilet paper.

**Comment by kai-li-wop** [comment]
Duplicate of #28

**Comment by kai-li-wop** [comment]
Should be fixed with 3bf1d822eeb36b3525d14fabe6773a35cd7aa217.
