### ISSUE TITLE
Crosshair and automated Mashine gun energy bar in ctl

### ISSUE THREAD

**Issue by MancusNemo** [PadWorld-Entertainment/worldofpadman#59]
Hello,

look at the energy bar over or on top of the automated Machine gun you can build in Capture the Lolly mode. Now put the Crosshair on the energy bar of the Machine gun and it turns it colour into it of the energy bar.
![Bildschirmfoto vom 2021-11-28 16-15-44](https://user-images.githubusercontent.com/73421306/143774062-cd7c1011-a3b0-43ae-ac92-f507c3592076.png)
![Bildschirmfoto vom 2021-11-28 16-16-04](https://user-images.githubusercontent.com/73421306/143774063-afa9ce75-3c64-409d-89cd-e7238a980f8e.png)

**Comment by mgerhardy** [comment]
`CG_Draw2D` is rather huge - I will try to split it up to ease the reordering without breaking stuff

the relevant part is `CG_DrawBambamIcon` which should come before `CG_DrawCrosshair`

**Comment by mgerhardy** [comment]
Since dd112587dea0b2f96c243faa1c688e5ffa41de4f it would be `CG_DrawEntityIcons()` call that should either happen before `CG_DrawCrosshair()` or vice versa.

**Comment by kai-li-wop** [comment]
@mgerhardy: I just tested your changes and found out while playing from 2 clients on a LAN server that the health bar of the BAMBAM is not shown any more. It is completely missing. Health of your own team's BAMBAMs should be indicated. I am not sure if it was also indicated of opposing team's BAMBAMs. Need to check for that.

**Comment by kai-li-wop** [comment]
I think with bc0e809eab408741626a9f42744b078a85b3c335 I fixed the issue that entity icons were not shown to players any more. So those "help/hint" icons of health stations, SYC teleporter and BB boxes should work again. This should also apply to the BamBam health bar, which I could not test right now. I think it is possible to test if the crosshair and health bar order is correct now, which was the task stated the original issue.

**Comment by 3aTmE** [comment]
![Image](https://user-images.githubusercontent.com/84514074/177042354-dc334843-d7c1-47e5-8e54-b302b4be6fdc.jpg)

I can Confirm the Issue as fixed ! 👍

**Comment by kai-li-wop** [comment]
@3aTmE: Is the crosshair in front of the energy bar of the bambam for sure? Maybe to test with some of the opaque crosshairs instead of the semitransparent wop design crosshairs. I cannot distinguish from the screenshot if the crosshair is in front of behind the energy bar.

**Comment by kai-li-wop** [comment]
Ok, just tested it myself with an opaque crosshair. Looks good so far.

![shot0002](https://user-images.githubusercontent.com/44040989/177299152-6c100349-6a2c-4ec3-9166-a76f6dcceeb3.jpg)
