### ISSUE TITLE
UI: Unknown command 'selectlogo' in player menu

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#82]
Console keeps spamming "unknown command 'selectlogo'" after changing the spray logo and leaving the player menu. This does also occur in WoP 1.6!

**Comment by mgerhardy** [comment]
This is in `PlayerSettings_SaveChanges`. The command is executed on the client side. I think this can be removed - as the logo is selected in the cgame code and there you are connected to the server the the "selectlogo" server command is sent properly.
